### ISSUE TITLE
IIS Express hosting System.Security.Cryptography.CryptographicException

### ISSUE THREAD

**Issue by davidmrichter** [IdentityServer/IdentityServer3#1057]
Hello

I took the identityserver3 WSFEderation Example and tried to host it on IIS

Now I get the folllowing error
System.Security.Cryptography.CryptographicException was unhandled by user code

  HResult=-2147024883
  Message=The data is invalid.
  Source=System.Security
  StackTrace:

       at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)

       at System.Security.Cryptography.DpapiDataProtector.ProviderUnprotect(Byte[] encryptedData)

       at System.Security.Cryptography.DataProtector.Unprotect(Byte[] encryptedData)

       at Microsoft.Owin.Security.DataProtection.DpapiDataProtector.Unprotect(Byte[] protectedData) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0

       at Thinktecture.IdentityServer.Core.Configuration.Hosting.HostDataProtector.Unprotect(Byte[] data, String entropy) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Configuration\Hosting\HostDataProtector.cs:line 39

       at Thinktecture.IdentityServer.Core.Configuration.Hosting.DataProtectorAdapter.Unprotect(Byte[] protectedData) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Configuration\Hosting\DataProtectorAdapter.cs:line 37

       at Microsoft.Owin.Security.DataHandler.SecureDataFormat`1.Unprotect(String protectedText) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer3\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0

  InnerException:

Actually everything remained the same, except the IIS hosting.
If I do hit continue the token gets issued normally and I can use my client as before. Strange!
Any idea what I missed? 
![error](https://cloud.githubusercontent.com/assets/9887781/6576442/9d4fbdc0-c737-11e4-892d-fcc0fa2899b5.png)

**Comment by loctanvo** [comment]
An old cookie? Cookie values are encrypted, and if the encryption key changes, an error will occur during decryption.

**Comment by leastprivilege** [comment]
yep - try deleting old cookies

**Comment by davidmrichter** [comment]
I did Delete All in IE- not better

**Comment by mschulz531** [comment]
did you double check the password on the certificate that you load?

**Comment by davidmrichter** [comment]
I used the certificate in the Config Folder of the Selfhosting project; never prompted to type in any password

**Comment by davidmrichter** [comment]
infact the sample is running; I 'll try to resetup the project

**Comment by davidmrichter** [comment]
I took the WebHost sample Project, which works !!; did some renaming; copied it into our solution folder; Add existing project; added WS Federation Plugin and corresponding configs

Same Exception!!

Anyone any further ideas?

**Comment by leastprivilege** [comment]
any updates?

**Comment by huysentruitw** [comment]
Got the same problem during tests on localhost. I went to chrome://settings/cookies and deleted the cookies for localhost. Problem fixed.

But how is it possible that the encryption key changes? I'm using IIS Express with the IIS Express Development Certificate. The only thing that happened before this problem were Windows updates...

**Comment by leastprivilege** [comment]
ASP.NET machine key is used to crypto. That *can* change if it is not set to a fixed value.
