### ISSUE TITLE
Question on certificate for Signing Tokens

### ISSUE THREAD

**Issue by skatukojwala** [IdentityServer/IdentityServer3#1151]
We found some interesting article about pfx files, 
http://security.stackexchange.com/questions/29425/difference-between-pfx-and-cert-certificates 

We are trying to get rid of dependency on pfx, instead use the certificate generate powered by 
BouncyCastle.Crypto(https://www.bouncycastle.org/), but we are getting errors while loading this

Please see the logs that generating from this. 

04/07/15 09:54:50.244   W [T-1] - [Thinktecture.IdentityServer.Core.Configuration.IdentityServerServiceFactory]: 4/7/2015 4:54:50 PM +00:00 -- AuthorizationCodeStore not configured - falling back to InMemory
04/07/15 09:54:50.251   W [T-1] - [Thinktecture.IdentityServer.Core.Configuration.IdentityServerServiceFactory]: 4/7/2015 4:54:50 PM +00:00 -- ConsentStore not configured - falling back to InMemory
04/07/15 09:54:50.533   I [T-13] - [Thinktecture.IdentityServer.Core.Endpoints.DiscoveryEndpointController]: 4/7/2015 4:54:50 PM +00:00 -- Start discovery request
04/07/15 09:54:50.640   I [T-16] - [Thinktecture.IdentityServer.Core.Endpoints.DiscoveryEndpointController]: 4/7/2015 4:54:50 PM +00:00 -- Start key discovery request
04/07/15 09:55:02.546   I [T-10] - [Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController]: 4/7/2015 4:55:02 PM +00:00 -- Start token request
04/07/15 09:55:02.569   I [T-10] - [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 4/7/2015 4:55:02 PM +00:00 -- Start client validation
04/07/15 09:55:02.577   I [T-10] - [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 4/7/2015 4:55:02 PM +00:00 -- Client validation success
 {
}
04/07/15 09:55:02.581   I [T-10] - [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 4/7/2015 4:55:02 PM +00:00 -- Start token request validation
04/07/15 09:55:02.585   I [T-10] - [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 4/7/2015 4:55:02 PM +00:00 -- Start password token request validation
04/07/15 09:55:02.743   I [T-10] - [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 4/7/2015 4:55:02 PM +00:00 -- Password token request validation success.
04/07/15 09:55:02.748   I [T-10] - [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 4/7/2015 4:55:02 PM +00:00 -- Token request validation success
 {
  "AuthenticationContextReferenceClasses": []
}
04/07/15 09:55:02.750   I [T-10] - [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 4/7/2015 4:55:02 PM +00:00 -- Creating token response
04/07/15 09:55:02.751   I [T-10] - [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 4/7/2015 4:55:02 PM +00:00 -- Processing token request
04/07/15 09:55:02.755   I [T-10] - [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 4/7/2015 4:55:02 PM +00:00 -- Creating access token
04/07/15 09:55:02.761   I [T-10] - [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 4/7/2015 4:55:02 PM +00:00 -- Creating JWT access token
04/07/15 09:55:02.795   E [T-10] - [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 4/7/2015 4:55:02 PM +00:00 -- Unhandled exception
System.InvalidOperationException: IDX10614: AsymmetricSecurityKey.GetSignatureFormater( 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' ) threw an exception.
Key: 'System.IdentityModel.Tokens.X509AsymmetricSecurityKey'
SignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', check to make sure the SignatureAlgorithm is supported.
Exception:'System.Security.Cryptography.CryptographicException: Key does not exist.

   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider.get_CspKeyContainerInfo()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetSignatureFormatter(String algorithm)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0'.
If you only need to verify signatures the parameter 'willBeUseForSigning' should be false if the private key is not be available. ---> System.Security.Cryptography.CryptographicException: Key does not exist.

   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider.get_CspKeyContainerInfo()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetSignatureFormatter(String algorithm)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateForSigning(SecurityKey key, String algorithm) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.CreateSignature(String inputString, SecurityKey key, String algorithm, SignatureProvider signatureProvider) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.WriteToken(SecurityToken token) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenSigningService.CreateJsonWebToken(Token token, SigningCredentials credentials) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 81
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenSigningService.SignTokenAsync(Token token) in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 55
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService.<CreateSecurityTokenAsync>d__c.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultTokenService.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator.<CreateAccessTokenAsync>d__20.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\ResponseHandling\TokenResponseGenerator.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator.<ProcessTokenRequestAsync>d__10.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\ResponseHandling\TokenResponseGenerator.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator.<ProcessAsync>d__0.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\ResponseHandling\TokenResponseGenerator.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<ProcessAsync>d__5.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Endpoints\Connect\TokenEndpointController.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<Post>d__0.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Endpoints\Connect\TokenEndpointController.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http910146.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\ballen\github\thinktecture\IdSrv3\Thinktecture.IdentityServer.v3\source\Core\Services\Default\DefaultLocalizationService.cs:line 0

**Comment by brockallen** [comment]
I don't understand your concern -- it's well known that pfx files have the private key and thus you should be storing the signing keys in the machine certificate store provided and secured by the OS.

**Comment by skatukojwala** [comment]
Thank you Allan for quick response.  We are trying to replace the pfx file with our own certificate generator. We are generating these certificates on the fly and storing the certificate in machine certificate store. But the identity server is failing to use this certificate for signing the token. 

I am not sure why it is failing from the log!.

**Comment by skatukojwala** [comment]
You guys used to have a great Tutorial dealing with Certificates right?.  I am not able to find the link again. Any idea?

**Comment by brockallen** [comment]
Dominick's PS video on Securing Web API -- the first section from that is all about HTTP and IIS security.

**Comment by brockallen** [comment]
I don't know about certs generated from your own cert generator. Why not just use makecert -- it's part of the windows SDK and works fine.

**Comment by brockallen** [comment]
Also, you don't need certs from a trusted CA for signing. You only need a trusted CA when creating SSL certificates.

**Comment by skatukojwala** [comment]
Sure, We are just trying to replace the Pfx file with certificate generator.

**Comment by brockallen** [comment]
You'd have to ask whoever created your certificate generator.

**Comment by loctanvo** [comment]
@skatukojwala Just keep in mind that the embedded .pfx provided is just for quick starting the samples. In your production environment, you want to use your own, and probably have the certificate stored in the machine cert store.

Not sure why you need to generate certs on the fly; doesn't seem quite right to me (but you probably have your reason for that). In your log, I see several `Key does not exist` messages. Usually this means that the private key is not accessible from the certificate. Ensure that the user running the process (IIS user?) has the access rights needed to load the cert.

**Comment by skatukojwala** [comment]
Sure, We were taking some approach of automatically load certificate from store or generating certificate at run time the the AuthSvr starts,  This certificate that we are generating was not working. 

Today we decided to generate pfx file as part of installation and store the file with binaries.  

For our test purposes we used following commands to generate pfx file that still does not work!. 

Makecert -sv MyTestpkey.pvk -n "cn=MySubject" MyTestCert.cer -b 01/01/
2015 -e 01/01/2015 -r

pvk2pfx -sv MyTestpkey.pvk -spc MyTestCert.cer -pfx MyTestPfx.pfx -po
test123

But unfortunately this fails too. 
Apologize for any bad questions! I am just trying to get my work done as per my schedule.

**Comment by brockallen** [comment]
Well, first thing is that I see you've set the expiration at Jan 1, 2015, which was some 4 months ago.

**Comment by skatukojwala** [comment]
I changed that but still it does not work!. I see the certificate getting loaded.
Are there any fields that are going to be very important in the Pfx file that we are generating.

**Comment by brockallen** [comment]
Perhaps this will help: https://technet.microsoft.com/en-us/library/cc780178%28v=ws.10%29.aspx

**Comment by loctanvo** [comment]
We ran this (I just made up some dates):

`makecert -r -pe -n "CN=some.name" -b 01/01/2000 -e 01/01/2020 -eku 1.3.6.1.5.5.7.3.1 -ss my -sr localMachine -sky exchange -sp "Microsoft RSA SChannel Cryptographic Provider" -sy 12`

In our case, the certificate was installed on the local computer cert store. We then exported the .pfx from there. Hence, we didn't go through the pvk2pfx step.

**Comment by DerAlbertCom** [comment]
If you load the Key from the Certificate Store, you must also load the private key. That's not that simple ;)

 * The Account which runs the Application must have Access to the private key

 * The Private Key must be marked as exportable

Now you can export the Bytes including the private key, and generate the X509Certificate.

```
        var cert = TheCertFromStore();
        if (cert != null && cert.HasPrivateKey)
                {
                    var password = Guid.NewGuid().ToString();
                    byte[] certBytes = cert.Export(X509ContentType.Pkcs12, password);
                    cert = new X509Certificate2(certBytes, password, X509KeyStorageFlags.MachineKeySet);
                }
```

With that IdServ3 works for me.

**Comment by skatukojwala** [comment]
using this tool which comes with source code  http://blog.pluralsight.com/selfcert-create-a-self-signed-certificate-interactively-gui-or-programmatically-in-net

Thanks to Keith Sparkjoy(http://blog.pluralsight.com/author/keithbrown42) for writing a great tool. 
I was able to generate a pfx file that can be used with Identity Server.

**Comment by skatukojwala** [comment]
Albert

We are planning to store these certificates into Certificate Store. 
How did you setup this PFX with respect to account.   I was able to create PFX Signature file and save it to Client Store but while retrieving the certificate it did not need any password. How did you setup to use password and map to account?.   Which StoreName and StoreLocation did you store under.

**Comment by arjan-amsterdam** [comment]
correct store is My/Local Machine, My shows as personal in MMC. I used a powersheel certificate which did not work with idsrv (unable to acccess private key error on startup). Generating the certificate using selfCert solved the issue, Thanks for ms for another lost day :(
