### ISSUE TITLE
Identity server autofac exceptions PROD

### ISSUE THREAD

**Issue by alin-nemet** [IdentityServer/IdentityServer3#1167]
Hi, we have recently deployed id srv in our PROD environments and we noticed some exceptions that appeared right after we deployed, affecting customers who made the first requests. The exceptions look as follows:

2015-04-08 10:28:07,759 FATAL Thinktecture.IdentityServer.Core.Configuration.Hosting.AutofacContainerMiddleware: unhandled exception in Autofac middleware System.ObjectDisposedException: Cannot access a disposed object. Object name: 'System.Net.Http.HttpMessageInvoker'. at System.Net.Http.HttpMessageInvoker.CheckDisposed() at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) at System.Web.Http.Owin.HttpMessageHandlerAdapter.<InvokeCore>d__0.MoveNext() in c:\etc\Dropbox\identity\IdentityServer3\Core\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Owin.UseCookieAuthenticationExtension.<>c__DisplayClass6.<<ConfigureCookieAuthentication>b__4>d__8.MoveNext() in c:\etc\Dropbox\identity\IdentityServer3\Core\source\Core\Configuration\AppBuilderExtensions\ConfigureCookieAuthenticationExtension.cs:line 96 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext() in c:\etc\Dropbox\identity\IdentityServer3\Core\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext() in c:\etc\Dropbox\identity\IdentityServer3\Core\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext() in c:\etc\Dropbox\identity\IdentityServer3\Core\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Owin.Cors.CorsMiddleware.<Invoke>d__0.MoveNext() in c:\etc\Dropbox\identity\IdentityServer3\Core\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Thinktecture.IdentityServer.Core.Configuration.Hosting.AutofacContainerMiddleware.<Invoke>d__4.MoveNext() in c:\etc\Dropbox\identity\IdentityServer3\Core\source\Core\Configuration\Hosting\AutofacContainerMiddleware.cs:line 56

Is this a known issue or does it have something to do with our implementation? We have configured hybrid/implicit/code flows, so it's hard to know if the error is caused by the way a client makes the call, or is server configuration.

Thanks for any help.

**Comment by brockallen** [comment]
Can you provide the HTTP request that was made that triggers this exception? You'd need to enable the detailed Web API logging in IdSvr.

**Comment by leastprivilege** [comment]
Could you try turning on all logging (web api diag, http logging) - and see if you can repo - and then send the log?

— 
cheers
Dominick Baier


On 10 Apr 2015 at 16:48:40, Brock Allen (notifications@github.com) wrote:

Can you provide the HTTP request that was made that triggers this exception? You'd need to enable the detailed Web API logging in IdSvr.

**Comment by alin-nemet** [comment]
Hi, thanks for your time. We will do that as soon as possible and post here more details.
Cheers.

**Comment by alin-nemet** [comment]
Hi, I still don't have more verbose production logs, but I got something interesting from my localhost id srv. It seems that the fatal exception is immediately preceded by an error accessing /connect/authorize. Maybe this will help a bit, otherwise I'll have to wait till more DBG data available. Here are the two exceptions:

2015-03-16 13:51:08,816 ERROR Thinktecture.IdentityServer.Core.Configuration.Hosting.ErrorPageFilterAttribute: Exception accessing: /connect/authorize
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Web.Http.HostAuthenticationFilter.<AuthenticateAsync>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\DefaultViewService\EmbeddedAssetsViewLoader.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\DefaultViewService\EmbeddedAssetsViewLoader.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\DefaultViewService\EmbeddedAssetsViewLoader.cs:line 0
2015-03-16 13:51:09,147 FATAL Thinktecture.IdentityServer.Core.Configuration.Hosting.AutofacContainerMiddleware: unhandled exception in Autofac middleware
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<SendResponseContentAsync>d__20.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\DefaultViewService\EmbeddedAssetsViewLoader.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<InvokeCore>d__0.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Services\DefaultViewService\EmbeddedAssetsViewLoader.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.AutofacContainerMiddleware.<Invoke>d__4.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityServer.v3\Core\source\Core\Configuration\Hosting\AutofacContainerMiddleware.cs:line 56

**Comment by brockallen** [comment]
Perhaps relevant: http://stackoverflow.com/questions/22157596/asp-net-web-api-operationcanceledexception-when-browser-cancels-the-request

**Comment by alin-nemet** [comment]
Thanks a lot! Do you think a workaround will soon be available?

Cheers,
Alin

**Comment by brockallen** [comment]
I'm not saying that's the issue -- I'm just saying it might be relevant.

**Comment by brockallen** [comment]
Are you also using Kentor.OwinCookieSaver?

**Comment by alin-nemet** [comment]
Yes,  we are in fact using kentor middlware to solve some cookies issue. Do you think it might cause or be related with the above problem?

**Comment by alin-nemet** [comment]
Actually, we upgraded recently to the most recent version of id server and removed kentor. But we were using it before the upgrade.

**Comment by brockallen** [comment]
I just saw the Kentor MW in another customer's project and it was causing the reset. Removing it fixed the problem.

**Comment by brockallen** [comment]
So are you still seeing the resets after removing Kentor?

**Comment by alin-nemet** [comment]
yes, we continue to see the exceptions in the logs.

**Comment by alin-nemet** [comment]
we will continue to investigate and post here any conclusions. Thx!

**Comment by brockallen** [comment]
We're still having a hard time being able to consistently reproduce this. If you can, please let us know.

**Comment by jawadatgithub** [comment]
I just found new case that cause same issue:

>2015-05-05 16:14:15.6292|INFO|End session callback requested
2015-05-05 16:14:15.7893**|FATAL|unhandled exception in Autofac middleware**

Follow below 4 steps to reproduce:
 
- Setting PublicOrigin to FrontEnd Server.
- Set PostSignOutAutoRedirectDelay to zero as below.

```c#
AuthenticationOptions = new AuthenticationOptions()
                    {
                        EnablePostSignOutAutoRedirect = true,
                        PostSignOutAutoRedirectDelay = 0
                    },
```
- login using ImplicitClient javascript Sample.
- call core/connect/endsession with id_token_hint & post_logout_redirect_uri from JavaScript ImplicitClient.


Note: 
if I don't use PublicOrigin, Autofac fatal error not thrown.
if I use delay value = 5, Autofac fatal error not thrown.

**Comment by brockallen** [comment]
Ok, thanks -- I'll see if I can repro it.

**Comment by imperugo** [comment]
I've  similar problem with the issue #1301 but I don't have ```EnablePostSignOutAutoRedirect```set to true.

So probably there is something else.

**Comment by brockallen** [comment]
Yep, that's ok -- end of this week when I get some time I'll be trying to repro both of them. Thanks for reporting it.

**Comment by brockallen** [comment]
Dup of #1141 -- closing to consolidate
