### ISSUE TITLE
"CryptographicException: Invalid provider type specified" when trying to authorize with self-signed certificate

### ISSUE THREAD

**Issue by hloken** [IdentityServer/IdentityServer3#1289]
Trying to get authentication to work with a self-signed certificate in a simple Asp.Net-based web-app (very similar to example http://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html).
When being re-directed after login i get an I get an unspecified error. 

Looking at the trace I can see that "Exception:'System.Security.Cryptography.CryptographicException: Invalid provider type specified." seems to be the root cause.

Is this a problem with my certificate or am I just doing it wrong? :-) Appreciate any help.

Semi-full trace follows:
```
Thinktecture.IdentityServer.Core.Configuration.Hosting.ErrorPageFilterAttribute: Exception accessing: /identity/connect/authorize
System.InvalidOperationException: IDX10614: AsymmetricSecurityKey.GetSignatureFormater( 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' ) threw an exception.
Key: 'System.IdentityModel.Tokens.X509AsymmetricSecurityKey'
SignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', check to make sure the SignatureAlgorithm is supported.
Exception:'System.Security.Cryptography.CryptographicException: Invalid provider type specified.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetSignatureFormatter(String algorithm)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0'.
If you only need to verify signatures the parameter 'willBeUseForSigning' should be false if the private key is not be available. ---> System.Security.Cryptography.CryptographicException: Invalid provider type specified.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetSignatureFormatter(String algorithm)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateForSigning(SecurityKey key, String algorithm) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.CreateSignature(String inputString, SecurityKey key, String algorithm, SignatureProvider signatureProvider) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.WriteToken(SecurityToken token) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenSigningService.CreateJsonWebToken(Token token, SigningCredentials credentials) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 81
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenSigningService.SignTokenAsync(Token token) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 55
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService.<CreateSecurityTokenAsync>d__c.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\Default\DefaultTokenService.cs:line 210
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by loctanvo** [comment]
Sounds like a cert error. How did you generate the certificate? If you used makecert, do you remember all the options you provided?

**Comment by hloken** [comment]
Thanks for the reply. I did it using Powershell's New-SelfSignedCertificate cmdlet, as described here. I basically used the options as described in the article so there is a high possibility that I've done it wrong. :-)

**Comment by vidarkongsli** [comment]
You might want to try to generate the self-signed key using [this script](https://gallery.technet.microsoft.com/scriptcenter/Self-signed-certificate-5920a7c6) like described in the blog post here: http://blog.is4u.be/2015/03/visual-c-rsa-encryption-using.html

**Comment by hloken** [comment]
Thanks for the reply, I will shortly be returning to solving this problem so I'll see if I can get to the bottom of it.

**Comment by paululvinius** [comment]
If anyone is still trying to solve this: you also need to supply KeyExportPolicy and Provider like this:

$SelfSignedCert = New-SelfSignedCertificate -DnsName $ApplicationDisplayName -CertStoreLocation cert:\LocalMachine\My -KeyExportPolicy Exportable -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" 

Found this code snippet here: https://azure.microsoft.com/en-us/documentation/articles/automation-sec-configure-azure-runas-account/#update-an-automation-account-using-powershell

**Comment by gregfiske** [comment]
I found a simpler way to specify the key provider.  If KeySpec to set to be 'Signature' then it will use a "legacy CSP" that IdentityServer3 can handle.

This cert made here worked for me in the demo in place of the test cert:
`New-SelfSignedCertificate -CertStoreLocation Cert:\CurrentUser\My -subject MyCert -KeyExportPolicy Exportable -NotAfter (Get-Date).AddYears(10) -Type CodeSigningCert -KeySpec Signature`
