### ISSUE TITLE
EF provider and logout

### ISSUE THREAD

**Issue by Blastnsmash** [IdentityServer/IdentityServer3#1311]
I am using the EF providers for Client, Scopes and users - and so far everything seems to work correctly except logging out. The following is taken from the JavaScript Implicit Client - TokenManager.

I am able to login, see id token contents, access token an use the call service button. 

When I log out the following is logged through diagnostics:

SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.LogoutResult]: 5/5/2015 5:00:24 PM +00:00 -- Redirecting to logout page
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 5/5/2015 5:00:24 PM +00:00 -- Logout prompt for subject: c53eb2d0-f66b-4053-a723-e6da808d6b10
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 5/5/2015 5:00:24 PM +00:00 -- EnableSignOutPrompt set to true, rendering logout prompt
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 5/5/2015 5:00:27 PM +00:00 -- Logout endpoint submitted
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 5/5/2015 5:00:27 PM +00:00 -- Logout requested for subject: c53eb2d0-f66b-4053-a723-e6da808d6b10
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 5/5/2015 5:00:27 PM +00:00 -- Clearing cookies
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 5/5/2015 5:00:27 PM +00:00 -- rendering logged out page
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.EndSessionController]: 5/5/2015 5:00:27 PM +00:00 -- End session callback requested
SelfHost.vshost.exe Error: 0 : FATAL : [Thinktecture.IdentityServer.Core.Configuration.Hosting.AutofacContainerMiddleware]: 5/5/2015 5:00:27 PM +00:00 -- unhandled exception in Autofac middleware
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.GetCallCancelled()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.get_CallCancelled()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.PropertiesTryGetValue(String key, Object& value)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.TryGetValue(String key, Object& value)
   at Microsoft.Owin.OwinRequest.Get[T](String key) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at Microsoft.Owin.OwinRequest.get_CallCancelled() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<InvokeCore>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Owin.UseCookieAuthenticationExtension.<>c__DisplayClass6.<<ConfigureCookieAuthentication>b__4>d__8.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureCookieAuthenticationExtension.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Owin.Cors.CorsMiddleware.<Invoke>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.AutofacContainerMiddleware.<Invoke>d__4.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\Hosting\AutofacContainerMiddleware.cs:line 56

Any idea why this is referring to InMemoryClientStore when using EF providers?

**Comment by Blastnsmash** [comment]
ConfigureCookieAuthenticationExtension.cs Line 97

 if (String.IsNullOrWhiteSpace(options.Path))
            {
                app.Use(async (ctx, next) =>
                {
                    // we only want this to run once, so assign to null once called 
                    // (and yes, it's possible that many callers hit this at same time, 
                    // but the set is idempotent)
                    if (setCookiePath != null)
                    {
                        setCookiePath(ctx.Request.PathBase.Value);
                        setCookiePath = null;
                    }
                    await next();
                });
            }


ctx = {Microsoft.Owin.OwinContext}
next = Target -> {Microsoft.Owin.Extensions.UseHandlerMiddleware..}

Values = '((((Microsoft.Owin.Extensions.UseHandlerMiddleware..)(((System.Delegate)(next)).Target)).context).Environment).Values' threw an exception of type 'System.ObjectDisposedException'

Message = "The CancellationTokenSource has been disposed."

((Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment)((((Microsoft.Owin.Extensions.UseHandlerMiddleware..)(((System.Delegate)(next)).Target)).context).Environment)).RequestId = 00000000-0000-0000-ee01-0080020000fe



--------------------------------------------------------------------------------------------------------------------------------------------Stack Trace
((System.Exception)(((Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment)((((Microsoft.Owin.Extensions.UseHandlerMiddleware..)(((System.Delegate)(next)).Target)).context).Environment)).CallCancelled)).StackTrace

   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.OwinHttpListenerContext.GetCallCancelled()
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.CallEnvironment.get_CallCancelled()

**Comment by brockallen** [comment]
Dup of #1141 -- closing to consolidate

**Comment by Blastnsmash** [comment]
v1.6 seems to have fixed the issue.

**Comment by brockallen** [comment]
Good to hear.
