### ISSUE TITLE
OWIN app path map breaks references

### ISSUE THREAD

**Issue by gilm0079** [IdentityServer/IdentityServer3#1313]
I've seen some of the ID server samples use the OWIN IAppBuilder Map method to start the ID server app at a virtual directory (ie. /core).  I'm not sure if I'm missing something, but if I do this I get errors in Visual Studio are runtime about not being able to find certain source .cs files.  I tried building a new VS MVC / web.api solution and ported the code over and same thing.  

When I use the map method and hit the /core page in my browser VS throws exceptions.

RequireSslMiddleware.cs not found

Exception Details:
Message: Error occurred during a cryptographic operation.
Stack Trace:    at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.HomogenizeErrors(Func`2 func, Byte[] input)
   at System.Web.Security.Cryptography.HomogenizingCryptoServiceWrapper.Unprotect(Byte[] protectedData)
   at System.Web.Security.MachineKey.Unprotect(ICryptoServiceProvider cryptoServiceProvider, Byte[] protectedData, String[] purposes)
   at System.Web.Security.MachineKey.Unprotect(Byte[] protectedData, String[] purposes)
   at Microsoft.Owin.Host.SystemWeb.DataProtection.MachineKeyDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.Owin.Security.DataProtection.AppBuilderExtensions.CallDataProtectionProvider.CallDataProtection.Unprotect(Byte[] protectedData) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.HostDataProtector.Unprotect(Byte[] data, String entropy) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\Hosting\HostDataProtector.cs:line 39
   at Thinktecture.IdentityServer.Core.Configuration.Hosting.DataProtectorAdapter.Unprotect(Byte[] protectedData) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\Hosting\DataProtectorAdapter.cs:line 37
   at Microsoft.Owin.Security.DataHandler.SecureDataFormat`1.Unprotect(String protectedText) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\InMemory\InMemoryClientStore.cs:line 0

Any ideas why I would be getting this using the Map method?  I'm using the latest stable Identity Server 3 nuget packages and Membership Reboot packages.  ID Server is currently 1.5.0.  I also tried to downgrade to 1.4.2 and 1.1.0 and I get the same results.  My VS 2003 debug is using IIS Express on Win 8.1 Pro and I'm running the site on SSL.  Thanks in advance.

**Comment by johnkors** [comment]
Never seen that before :/ Strange if it has anything to do with Katanas map. I would check that the references are actually going to the nuget dlls. Seems like something is a bit off. Did you reference the source dlls directly from your own build at one point?

**Comment by gilm0079** [comment]
I double checked all the reference paths and they all check out.  I even created a new solution yesterday to make sure I wasn't missing something.  Cleaned the solution.  Verified the bin folder was wiped out.  I'm at a loss.  Any other ideas?  fyi. Those paths in the stack trace are not mine. I'm guessing they are brock's as they have a ballen folder on the c drive?

**Comment by gilm0079** [comment]
I had a co-worker load up my solution and it worked so it was something with my machine.  I found this issue https://github.com/IdentityServer/IdentityServer3/issues/1057.  I tried before to dump cookies using chrome's developer tools, but that must not work completely.  I used the chrome://settings/cookies menu to dump the cookies and that fixed it.
