### ISSUE TITLE
Certificate Woes

### ISSUE THREAD

**Issue by scottrudy** [IdentityServer/IdentityServer3#1320]
I am trying to load the pfx via:

    new X509Certificate2(string.Format(@"{0}bin\idsrv3test.pfx",
        AppDomain.CurrentDomain.BaseDirectory), "idsrv3test");

However, I am getting the following error

    Cannot find the requested object.
    at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
    at System.Security.Cryptography.X509Certificates.X509Utils._QueryCertFileType(String fileName)
    at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromFile(String fileName, Object password, X509KeyStorageFlags keyStorageFlags)
    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password)
    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
    at IdentityServer.Startup.LoadCertificate() in c:\Users\srudy\Documents\Visual Studio 2013\Projects\IdentityServer\IdentityServer\Startup.cs:line 36
    at IdentityServer.Startup.<Configuration>b__1(IAppBuilder idsrvApp) in c:\Users\srudy\Documents\Visual Studio 2013\Projects\IdentityServer\IdentityServer\Startup.cs:line 22
    at Owin.MapExtensions.Map(IAppBuilder app, PathString pathMatch, Action`1 configuration)
    at Owin.MapExtensions.Map(IAppBuilder app, String pathMatch, Action`1 configuration)
    at IdentityServer.Startup.Configuration(IAppBuilder app) in c:\Users\srudy\Documents\Visual Studio 2013\Projects\IdentityServer\IdentityServer\Startup.cs:line 20

**Comment by scottrudy** [comment]
Never mind, I found the problem. It seems downloading a PFX through the browser in Win 7 doesn't work. I actually had to use Git to pull the file down.

**Comment by tjoudeh** [comment]
@scottrudy Happened for me too, thanks for answering the issue!

**Comment by steven-gruverman** [comment]
@scottrudy Me, three. Certificates, grr.

**Comment by mattGuima** [comment]
OH.My.FU***.GAWD. thank you so much. what the hell?? I even did the "unblock" thing remembering that it does that these days when you download files from the web, but even that didn't do anything. does it actually change the contents when downloading? weird!
