### ISSUE TITLE
Operational Data issue when using Entity framework.

### ISSUE THREAD

**Issue by Mario121** [IdentityServer/IdentityServer3#1453]
I am using the example clients (WPF Hybrid Client and MVC Hybrid), along with the Entityframework  example that come in the sample code. If i do a "Login with Profile and long-lived Access Token"  in the WPF Client, it returns a code, id_token, access_token etc. If i then click on the "Use Code" button, I receive the following when RequestAuthorizationCodeAsync is called; 

![untitled-2](https://cloud.githubusercontent.com/assets/12775084/8019820/870a5a8a-0ca5-11e5-8ce3-7bfbc71ee1e0.png)

The interesting thing is, if i comment out the "factory.RegisterOperationalServices(efConfig);" line within the factory.cs class in the entityframework sample, the "Use Code" button works and returns a refresh token. 

The following database tables have been created.
![untitled-3](https://cloud.githubusercontent.com/assets/12775084/8019864/74122da2-0ca7-11e5-952c-944a8fd201e4.png)

I am seeing tokens appear in the database
![untitled-4](https://cloud.githubusercontent.com/assets/12775084/8019865/84e45ff6-0ca7-11e5-9988-3e0b04b188cf.png)

Clients table contains
![untitled-6](https://cloud.githubusercontent.com/assets/12775084/8019871/c1c86d0e-0ca7-11e5-9191-2f214d3927eb.png)

My apologies if i have miss understood something. I am still trying to get my head around this.  

Trace.log:

SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 6/06/2015 2:03:08 PM +00:00 -- Start authorize request client validation
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.AuthorizeRequestValidator]: 6/06/2015 2:03:08 PM +00:00 -- Authorize request validation success
 {
  "ClientId": "hybridclient",
  "ClientName": "Hybrid Native Client Demo",
  "RedirectUri": "oob://localhost/wpfclient",
  "AllowedRedirectUris": [
    "oob://localhost/wpfclient"
  ],
  "SubjectId": "alice",
  "ResponseType": "code id_token token",
  "ResponseMode": "fragment",
  "Flow": "Hybrid",
  "RequestedScopes": "openid profile read write offline_access",
  "State": "random_state",
  "Nonce": "random_nonce",
  "SessionId": "4e4c5876e068d656a101538564a5e6a1",
  "Raw": {
    "client_id": "hybridclient",
    "response_type": "code id_token token",
    "scope": "openid profile read write offline_access",
    "redirect_uri": "oob://localhost/wpfclient",
    "state": "random_state",
    "nonce": "random_nonce"
  }
}
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeResponseGenerator]: 6/06/2015 2:03:08 PM +00:00 -- Creating Hybrid Flow response.
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.AuthorizeResponseGenerator]: 6/06/2015 2:03:09 PM +00:00 -- Creating Implicit Flow response.
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 6/06/2015 2:03:09 PM +00:00 -- Creating access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 6/06/2015 2:03:09 PM +00:00 -- Creating JWT access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 6/06/2015 2:03:09 PM +00:00 -- Creating identity token
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Services.Default.DefaultClaimsProvider]: 6/06/2015 2:03:09 PM +00:00 -- Getting claims for identity token for subject: alice
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 6/06/2015 2:03:09 PM +00:00 -- Creating JWT identity token
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthorizeEndpointController]: 6/06/2015 2:03:09 PM +00:00 -- End authorize request
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Results.AuthorizeRedirectResult]: 6/06/2015 2:03:09 PM +00:00 -- Redirecting to: oob://localhost/wpfclient
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController]: 6/06/2015 2:03:11 PM +00:00 -- Start token request
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 6/06/2015 2:03:11 PM +00:00 -- Start client validation
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 6/06/2015 2:03:11 PM +00:00 -- Client validation success
 {
  "ClientId": "hybridclient",
  "ClientName": "Hybrid Native Client Demo",
  "ClientCredentialType": "Basic"
}
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 6/06/2015 2:03:11 PM +00:00 -- Start token request validation
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 6/06/2015 2:03:11 PM +00:00 -- Start validation of authorization code token request
SelfHost.vshost.exe Error: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 6/06/2015 2:03:11 PM +00:00 -- Unhandled exception
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Thinktecture.IdentityServer.EntityFramework.Serialization.ScopeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Thinktecture.IdentityServer.EntityFramework.BaseTokenStore`1.ConvertFromJson(String json)
   at Thinktecture.IdentityServer.EntityFramework.BaseTokenStore`1.<GetAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator.<ValidateAuthorizationCodeRequestAsync>d__a.MoveNext() in c:\projects\thinktecture\source\Core\Validation\TokenRequestValidator.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator.<RunValidationAsync>d__5.MoveNext() in c:\projects\thinktecture\source\Core\Validation\TokenRequestValidator.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator.<ValidateRequestAsync>d__0.MoveNext() in c:\projects\thinktecture\source\Core\Validation\TokenRequestValidator.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<ProcessAsync>d__5.MoveNext() in c:\projects\thinktecture\source\Core\Endpoints\Connect\TokenEndpointController.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<Post>d__0.MoveNext() in c:\projects\thinktecture\source\Core\Endpoints\Connect\TokenEndpointController.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Threading.Tasks.System.Web.Http790585.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\projects\thinktecture\source\Core\Services\Default\DefaultCorsPolicyService.cs:line 0

**Comment by brockallen** [comment]
So there's a LINQ statement somewhere that's doing First or Single -- It's hard to tell, but can you get a sense where that's coming from?

**Comment by brockallen** [comment]
Any update?

**Comment by depl0y** [comment]
I have the same error happening for me (on 2.0.0), while rendering the permissions page.

Here's my stack trace:
https://gist.github.com/depl0y/3b347e93b00416ed80fa

As soon as I log in on my server to display my permissions page this exception is thrown,

**Comment by brockallen** [comment]
Can you open a new issue so we can track it (if you're still having issues) and describe your steps to reproduce? Thanks

**Comment by Mario121** [comment]
Sorry about the late reply, turns out the example puts a duplicate 'openid' entry into the scope table. This crashed the json serialiser when it did a .single() call.
