### ISSUE TITLE
Automatically login local user after registration

### ISSUE THREAD

**Issue by vinayhfs** [IdentityServer/IdentityServer3#1848]
Already this question is raised 2-3 times. I have gone through those issues still not clear how we can achieve "Automatically login local user after registration" with IdentityServer3.  My scenario is like this  User will come to registration page first (having anonymous access and this page will be hosted on identity server ) set his password on this page. Once he enter his password, user should be authenticated and should be redirected to client system. 
Can some explains how we can do this with IdentityServer3?

**Comment by brockallen** [comment]
Use the OWIN environment extensions from your custom registration page:

https://identityserver.github.io/Documentation/docsv2/advanced/owin.html

**Comment by vinayhfs** [comment]
Thank you for prompt response.  I am trying use IssueLoginCookie  method as below
 AuthenticatedLogin login = new AuthenticatedLogin
            {
                Name = user.Username,
                Subject = user.Subject,
                Claims = user.Claims,
                PersistentLogin = false,
                IdentityProvider = "idp",
                AuthenticationMethod = "amr",
                PersistentLoginExpiration = System.DateTimeOffset.Now.AddDays(1)
            };
            Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.IssueLoginCookie(Request.GetOwinContext().Environment, login);

But I am getting exception “Value cannot be null”.   

System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: context
  Source=Thinktecture.IdentityServer3
  ParamName=context
  StackTrace:
       at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:line 0
       at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType, IEnumerable`1 parameters) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:line 0
       at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:line 0
       at Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.ResolveDependency[T](IDictionary`2 env) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Extensions\OwinExtensions.cs:line 246
       at Thinktecture.IdentityServer.Core.Extensions.OwinExtensions.IssueLoginCookie(IDictionary`2 env, AuthenticatedLogin login) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Extensions\OwinExtensions.cs:line 129
       at Delogue.SSO.Controllers.HomeController.TestLogin() in c:\Vinay\W-GitHub\Code\delogue-sso\src\DelogueSSO\Controllers\HomeController.cs:line 71
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
       at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
       at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
  InnerException

**Comment by vinayhfs** [comment]
solved - Ref - https://github.com/IdentityServer/IdentityServer3/issues/1140
If there is better solution please let me know.

**Comment by henninga** [comment]
We considered automatically logging in the user, but rejected the idea for security reasons. By doing that, you're opening yourself up to mining the database for emails.

We redirect the user to login screen if the registration is successfull or if the email is already in use. We then send an email with further steps/info. A bit more hassle but we're not leaking user info.
