### ISSUE TITLE
Problem with custom view loader - value cannot be null

### ISSUE THREAD

**Issue by vidarkongsli** [IdentityServer/IdentityServer3#1897]
I have set up a custom view loader that worked well with version 1.6.2. Now, I am trying to switch to version 2.0.1. The custom view loader is basically a wrapper around FileSystemWithEmbeddedFallbackViewModel which contains certain logic. Now, it spits out the following error and stack trace. Any ideas?
```
System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at IdentityServer3.Core.Services.Default.AssetManager.LoadResourceString(String name) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\DefaultViewService\AssetManager.cs:line 100
   at IdentityServer3.Core.Services.Default.AssetManager.LoadPage(String pageName) in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\DefaultViewService\AssetManager.cs:line 43
   at IdentityServer3.Core.Services.Default.FileSystemWithEmbeddedFallbackViewLoader.<LoadAsync>d__0.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\DefaultViewService\FileSystemWithEmbeddedFallbackViewLoader.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at X.Id.IdSrv.CustomViewLoader.<LoadAsync>d__4.MoveNext() in C:\dev\github\X\src\X.Id\IdSrv\CustomViewLoader.cs:line 23
```

**Comment by loctanvo** [comment]
So the stream is null. Could it be related to [the assets folder being renamed to templates](https://github.com/IdentityServer/IdentityServer3/issues/1754)?

Otherwise, if you're on vNext, there seems to be a potential problem with the view loader.

**Comment by vidarkongsli** [comment]
You're right. Thanks!
