### ISSUE TITLE
Error during load test: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by vidarkongsli** [IdentityServer/IdentityServer3#2089]
We are load testing our IdSrv-based solution. It is hosed on IIS on Windows 2012 R2, .NET 4.5.2. We get the following error message now and then, and it seems that the application pool recycles as a result of this. Any ideas about what can be the cause of this?
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Security.Claims.ClaimsPrincipal.SelectPrimaryIdentity(IEnumerable`1 identities)
   at System.Security.Claims.ClaimsPrincipal.get_Identity()
   at IdentityServer3.Core.Extensions.InternalOwinExtensions.GetCurrentUserDisplayName(IOwinContext context) in c:\local\identity\server3\Core\source\Core\Extensions\InternalOwinExtensions.cs:line 289
   at IdentityServer3.Core.Endpoints.AuthenticationController.<RenderLoginPage>d__6a.MoveNext() in c:\local\identity\server3\Core\source\Core\Endpoints\AuthenticationController.cs:line 911
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdentityServer3.Core.Endpoints.AuthenticationController.<Login>d__1.MoveNext() in c:\local\identity\server3\Core\source\Core\Endpoints\AuthenticationController.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http851122.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
```

**Comment by vidarkongsli** [comment]
It seems (not 100% for sure) that the culprit was the following code we had in our customized `UserService`:
```
public override Task PreAuthenticateAsync(PreAuthenticationContext context)		
{		
    return Task.Run(() =>		
    {		
        _ctx.Authentication.User.AddIdentity(new ClaimsIdentity(new[] {new Claim("...", "...")}));		
        base.PreAuthenticateAsync(context);		 
    });		
}
```
So don't spend time investigating IdSrv with regards to this problem, but if anyone can share any insight in why this is bad to do, I would appreciate it greatly.

**Comment by brockallen** [comment]
Seems strange. Normally the incoming principal should only be access by one thread/task at a time, unless you're doing something unusual with parallel tasks (I doubt it though). 

The other thing this makes me wonder if if a ClaimsPrincipal/Identity is getting cached or reused across requests in some way.

**Comment by vidarkongsli** [comment]
Might it have to do with the fact that `_ctx` in the snippet above is initialized like so:
```c-sharp
private readonly IOwinContext _ctx;

public CustomUserService(CustomUserAccountService userSvc, OwinEnvironmentService env)
    : base(userSvc)
{
     _ctx = new OwinContext(env.Environment);
}
```

Maybe the code should rather be something like so:
```c-sharp
public override Task PreAuthenticateAsync(PreAuthenticationContext context)     
{       
    _ctx.Authentication.User.AddIdentity(new ClaimsIdentity(new[] {new Claim("...", "...")}));      
    return base.PreAuthenticateAsync(context);
}
```
Or, alternatively:
```c-sharp
public override async Task PreAuthenticateAsync(PreAuthenticationContext context)     
{       
    _ctx.Authentication.User.AddIdentity(new ClaimsIdentity(new[] {new Claim("...", "...")}));      
    await base.PreAuthenticateAsync(context).ConfigureAwait(false);     
}
```

**Comment by brockallen** [comment]
Is your user service registered as a singleton?

**Comment by vidarkongsli** [comment]
Nope.
```
factory.UserService = new Registration<IUserService, CustomUserService>();
```

**Comment by brockallen** [comment]
Ok, so still a mystery. Keep digging, I guess...

**Comment by leastprivilege** [comment]
progress?

**Comment by vidarkongsli** [comment]
We removed the entire `PreAuthenticateAsync` override, and that fixed the problem. I suspect that the problem was our failure to block or await the call to `base.PreAuthenticateAsync(context)`, but I don't really know. I might have the time to investigate that in detail later.

**Comment by johnkors** [comment]
Got the same error (idsrv v2.1.1) when rendering the loggedout view with the default viewservice.

```
2016-06-01 10:48:29.9993|ERROR|IdentityServer3.Core.Configuration.Hosting.LogProviderExceptionLogger|Unhandled exception System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at IdentityServer3.Core.Services.Default.DefaultViewService.BuildTags(String tagFormat, String basePath, IEnumerable`1 values) in c:\local\identity\server3\Core\source\Core\Services\DefaultViewService\DefaultViewService.cs:line 257
   at IdentityServer3.Core.Services.Default.DefaultViewService.BuildModel(CommonViewModel model, String page, IEnumerable`1 stylesheets, IEnumerable`1 scripts) in c:\local\identity\server3\Core\source\Core\Services\DefaultViewService\DefaultViewService.cs:line 239
   at IdentityServer3.Core.Services.Default.DefaultViewService.<Render>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Services\DefaultViewService\DefaultViewService.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Results.LoggedOutActionResult.<>c__DisplayClass2.<<.ctor>b__0>d__4.MoveNext() in c:\local\identity\server3\Core\source\Core\Results\LoggedOutActionResult.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Results.HtmlStreamActionResult.<Render>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Results\HtmlStreamActionResult.cs:line 37

```

**Comment by johnkors** [comment]
It might have to do with this:

[DefaultViewService` in v.2.1.1, line 257](https://github.com/IdentityServer/IdentityServer3/blob/2.1.1/source/Core/Services/DefaultViewService/DefaultViewService.cs#L257)

```
// 'values' here is either scripts or stylesheets coming from the options
string BuildTags(string tagFormat, string basePath, IEnumerable<string> values)
{
	if (values == null || !values.Any()) return String.Empty;

	var sb = new StringBuilder();
	foreach (var value in values) // <-- exception
...
```

My customviewservice
```
public class CustomViewService : DefaultViewService
{
	private readonly OwinEnvironmentService _owinservice;

	public IceIdentityViewService(DefaultViewServiceOptions options, IViewLoader viewLoader, OwinEnvironmentService owinservice) : base(options, viewLoader)
	{
		_owinservice = owinservice;
		config.Stylesheets.Add("~/../Content/site.css"); // I'm modifying this list in the ctor
	}
}
```

Registered via:

```
factory.Register(new DefaultViewServiceRegistration<CustomViewService >());
```

**Comment by vidarkongsli** [comment]
The `DefaultViewServiceOptions` type is registered in DI as a singleton. Yet, it has priperties (Stylesheets, Scripts) of a mutable type (IList). You are essentially mutating a singleton with `config.Stylesheets.Add(...`

**Comment by johnkors** [comment]
Yep, my thought as well. Moving the list modifications to startup instead of in the ctor.

**Comment by vidarkongsli** [comment]
I think the API should be changed here. The fact that `DefaultViewServiceRegistration` [registers a singleton of a mutable type ](https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Services/DefaultViewService/DefaultViewServiceRegistration.cs#L70) is somewhat bad. Either, it should not register it as a singleton, or the type should be immutable. The latter could be achieved making the properties of `DefaultViewServiceOptions` `ReadOnlyCollection<T>` or `IEnumerable<T>`

**Comment by johnkors** [comment]
Agreed. My HTML was also pretty funny as of this.

```
<!DOCTYPE html>
<html ng-app="app" ng-csp ng-controller="LayoutCtrl">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Ice Identity Server</title>
    <link href='/oauth2/assets/styles.min.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
<link href='/oauth2/../Content/site.css' rel='stylesheet'>
...
..
..
.
.
.
.
```

**Comment by brockallen** [comment]
Sorry, just catching up here. So I guess you're modifying the CSS collection in one of the overridden view service methods? YEa, obviously for now I'd suggest cloning the collection via ToArray or ToList for now and modify that.

**Comment by johnkors** [comment]
No, not in the methods, @brockallen, but in a ctor of a class inheriting the `DefaultViewService`. Same effect thou, you're right. Moving the modification of the list out of the ViewService alltogether is a workaround, yep. 

To avoid others doing the same stupid error I just did, I agree with @vidarkongsli 's solution changing those from IList to IEnumerable/IReadOnlyCollection could be nice.

Do you want a PR for this? Breaking change and all..

**Comment by brockallen** [comment]
Yea, breaking change plus those configuring it in Startup can't add to the collection unless we allow it a different way. Not sure what to do, but i"ll re-open a new issue here for 3.0 (since it would be a breaking change): https://github.com/IdentityServer/IdentityServer3/issues/2947

Also, as a side note, turns out there are similar issues in ASP.NET Core with their DI/configuration system that I just discovered this past week.
