### ISSUE TITLE
Question about Logout

### ISSUE THREAD

**Issue by aaabdul** [IdentityServer/IdentityServer3#2130]
When I logout (i.e. using endsession end point) I am getting the following error

IDX10709: 'jwtEncodedString' is not well formed: '7e5f9217e7076a920e65360b91cbf7e7'. The string needs to be in compact JSON format, which is of the form: '..'.

It's quite obvious it's because I am using reference token. Is it not possible to use log-out if I am using reference tokens instead of JWTs ?

**Comment by brockallen** [comment]
Where's the error from? IdSvr? If so, do you have a call stack from the log?

**Comment by aaabdul** [comment]
It is coming from the IdSvr. Following is the full stack trace I am getting. 

[IS3] :: System.ArgumentException: IDX10709: 'jwtEncodedString' is not well formed: '7e5f9217e7076a920e65360b91cbf7e7'. The string needs to be in compact JSON format, which is of the form: '<Base64UrlEncodedHeader>.<Base64UrlEncodedPayload>.<OPTIONAL, Base64UrlEncodedSignature>'.
   at System.IdentityModel.Tokens.JwtSecurityToken..ctor(String jwtEncodedString)
   at IdentityServer3.Core.Validation.TokenValidator.GetClientIdFromJwt(String token)
   at IdentityServer3.Core.Validation.TokenValidator.<ValidateIdentityTokenAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdentityServer3.Core.Validation.EndSessionRequestValidator.<ValidateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Endpoints.EndSessionController.<Logout>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http845002.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

**Comment by brockallen** [comment]
Ah, I bet you're passing the access token and not the id token at logout time. The id_token_hint param must be the original id_token returned from the authentication.

**Comment by aaabdul** [comment]
Ah! that's what I am doing wrong. How do I logout with Access Token ?

**Comment by brockallen** [comment]
You don't.

**Comment by aaabdul** [comment]
Should I be using revoke end point instead ?

**Comment by brockallen** [comment]
Depends what you're doing. Where is logout being triggered from? Some client app, right? So if that client app authenticated the user then it will have an id_token. Use that for sign out.

**Comment by aaabdul** [comment]
Yes the client is a web app that is going to be getting the access token from IdSvr to access the API. Client will be using password grant type and I am not sure if I can get ID token in password grant type. 

This is all I am getting. What I am trying to achieve is that after the client logs out of the web app I want to make sure the tokens issued are destroyed and not can't be used again. 

{
  "access_token": "263ac040cdcf95b094cf1ffd8bd932a2",
  "expires_in": 3600,
  "token_type": "Bearer",
  "refresh_token": "d6f8d0d12e9775b6de6815cf018c175f"
}

**Comment by brockallen** [comment]
Ah, and that's the problem -- you're using password grant type which is OAuth2 and OAuth2 doesn't have the concept of signout. So given your scenario, at logout time of the client, what are you trying to do at IdSvr? The user did not log into IdSvr, so there's no point in sending them to the end session endpoint. I think the only thing you can do is invalidate the access token, which would be the token revocation endpoint.

**Comment by aaabdul** [comment]
Thank you. That makes sense. Sort of what I thought initially to use revocation end point. 

I was trying to achieve this in the following link, but I am sure I am doing something wrong. 
https://identityserver.github.io/Documentation/docsv2/endpoints/revocation.html

Issued a POST to 
/connect/revocation
with 
client_id
client_secret
token
token_type_hint = access_token
in the body 

Getting back OK - 200 but when I use the same token to getuserinfo, I can get user information.

**Comment by brockallen** [comment]
If it's a JWT then there's no ability to revoke it.

**Comment by aaabdul** [comment]
It's not. It's an access token of type reference .

**Comment by brockallen** [comment]
Hmm, then something is odd. If you revoke the access token and it's a reference, then it's deleted from the DB. That means IdSvr won't have anything to look up. Perhaps it's being cached in IdSvr?

**Comment by aaabdul** [comment]
Yeah, it works fine after a PC reboot. Very odd!. Thanks Anyway.

**Comment by binarymist** [comment]
So how do you tell identityserver to destroy your token if you're using jwt? So I can never logout? Also what's an access token of type reference? I have a jwt which is an access token, what's with the type reference?

**Comment by leastprivilege** [comment]
http://leastprivilege.com/2015/11/25/reference-tokens-and-introspection/

**Comment by binarymist** [comment]
Thanks @leastprivilege. Do you have examples (working code) of how this is used in a working system?

**Comment by leastprivilege** [comment]
Check the clients sample in the samples repo

**Comment by binarymist** [comment]
Thanks.

It doesn't seem to matter if I change the ClientSecret to something invalid. I'm still authorised as long as my token is valid, so what exactly does the following code do?

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
    {
        Authority = "https://localhost:44333/core",
        RequiredScopes = new[] { "api1" },
 
        ClientId = "api1",
        ClientSecret = "secret"
    });

**Comment by leastprivilege** [comment]
with JWTs - or reference tokens?

**Comment by binarymist** [comment]
reference tokens, we've switched from JWTs.

**Comment by leastprivilege** [comment]
ClientId/Secret refer to the credentials set up for the scope. If they don't match - validation should not succeed.

**Comment by leastprivilege** [comment]
maybe it's best to open a new issue now when you have further questions.
