### ISSUE TITLE
Intermittent System.InvalidOperationException: IDX10614 exceptions on Azure Web Site

### ISSUE THREAD

**Issue by marcus-magnusson** [IdentityServer/IdentityServer3#2163]
Hello,

We're having some issues with a web app running as an Azure Web Site, with the following dependency:

package id="Thinktecture.IdentityServer3" version="1.2.1" targetFramework="net451"

This has been happening on and off since last week, sometimes with days in between, sometimes minutes. Restarting the web site solves the problem. We've been trying to trouble shoot but nothing yet. Any ideas? What we have in the error log is:

w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController]: 11/10/2015 11:40:41 AM +00:00 -- Start token request
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 11/10/2015 11:40:41 AM +00:00 -- Start client validation
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.ClientValidator]: 11/10/2015 11:40:41 AM +00:00 -- Client validation success
{
  "ClientId": "xxx",
  "ClientName": "app",
  "ClientCredentialType": "Basic"
}
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 11/10/2015 11:40:41 AM +00:00 -- Start token request validation
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 11/10/2015 11:40:41 AM +00:00 -- Start password token request validation
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 11/10/2015 11:40:41 AM +00:00 -- Password token request validation success.
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.Validation.TokenRequestValidator]: 11/10/2015 11:40:41 AM +00:00 -- Token request validation success
{
  "ClientId": "xxx",
  "ClientName": "app",
  "GrantType": "password",
  "Scopes": "api1 offline_access",
  "UserName": "xxxxxx-xxxx",
  "AuthenticationContextReferenceClasses": []
}
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 11/10/2015 11:40:41 AM +00:00 -- Creating token response
w3wp.exe Information: 0 : [Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator]: 11/10/2015 11:40:41 AM +00:00 -- Processing token request
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 11/10/2015 11:40:41 AM +00:00 -- Creating access token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 11/10/2015 11:40:41 AM +00:00 -- Creating refresh token
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultRefreshTokenService]: 11/10/2015 11:40:41 AM +00:00 -- Setting an absolute lifetime: 2592000
Debug: [Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService]: 11/10/2015 11:40:41 AM +00:00 -- Creating JWT access token
w3wp.exe Error: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.LogProviderExceptionLogger]: 11/10/2015 11:40:41 AM +00:00 -- Unhandled exception
System.InvalidOperationException: IDX10614: AsymmetricSecurityKey.GetSignatureFormater( 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' ) threw an exception.
Key: 'System.IdentityModel.Tokens.X509AsymmetricSecurityKey'
SignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', check to make sure the SignatureAlgorithm is supported.
Exception:'System.Security.Cryptography.CryptographicException: Keyset does not exist

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetSignatureFormatter(String algorithm)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures)'.
If you only need to verify signatures the parameter 'willBeUseForSigning' should be false if the private key is not be available. ---> System.Security.Cryptography.CryptographicException: Keyset does not exist

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetSignatureFormatter(String algorithm)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures)
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.SignatureProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.CreateSignature(String inputString, SecurityKey key, String algorithm, SignatureProvider signatureProvider)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenSigningService.CreateJsonWebToken(Token token, SigningCredentials credentials)
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenSigningService.SignTokenAsync(Token token)
   at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService.<CreateSecurityTokenAsync>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator.<CreateAccessTokenAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator.<ProcessTokenRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator.<ProcessAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<ProcessAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityServer.Core.Endpoints.TokenEndpointController.<Post>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http790585.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

**Comment by marcus-magnusson** [comment]
We updated to v. 1.6.3, so far so good, will keep this issue posted!

**Comment by leastprivilege** [comment]
Keyset does not exist typically points to problems with access rights to the private key.

**Comment by marcus-magnusson** [comment]
@leastprivilege Hey, thanks for the reply!

Yeah, we saw some people having problems like that. What's weird is that this application has been running fine in production for months, until last week when this problem suddenly started happening. We first thought it might've been an expired certificate, but that doesn't seem to be the case. Also, the certificate is included as a resource in the project, so we don't understand how the application would suddenly lose access rights to the private key. We're still scratching our heads here, will keep investigating and see what we can come up with.

**Comment by brockallen** [comment]
All set on this issue?

**Comment by marcus-magnusson** [comment]
Yeah, it would seem that way, the issue does seem to arrise sometimes when the app pool restarts, after which we for some reason can't access the private key anymore. I'd say it's unlikely to be related to IdentityServer3, so yes, please close this issue.

**Comment by josencv** [comment]
@marcus-magnusson Did you find the cause? Im having the same issue.

**Comment by jonbarthol** [comment]
@marcus-magnusson this issue just started up for me too about a week ago. Any ideas?

**Comment by marcus-magnusson** [comment]
@josencv @jonbarthol If I recall correctly, it was somehow related to how we were reading our certificate. Initially, we read it by doing

typeof(Certificate).Assembly.GetManifestResourceStream

but now we are reading it from the certificate store, as in

http://stackoverflow.com/questions/1205295/get-list-of-certificates-from-the-certificate-store-in-c-sharp

Hope that helps!
