### ISSUE TITLE
Unexpected character encountered while parsing value: C. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2226]
Hello,
I have idsrv3 server and works ok but in log i have regularly this error:

 ```[Error] Exception while deserializing address claim
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at IdentityServer3.Core.Extensions.ClaimListExtensions.GetValue(Claim claim)```

<!---
@huboard:{"order":2226.0,"milestone_order":2226,"custom_state":""}
-->

**Comment by leastprivilege** [comment]
Are you using address claims?

**Comment by leastprivilege** [comment]
I removed the address claim handling. In 2.2.1 you should not see this error anymore

**Comment by leastprivilege** [comment]
We have a new ClaimValueType.Json if you want to preserve JSON in claims.

**Comment by totpero** [comment]
good, thanks :+1:
