### ISSUE TITLE
Autofac - Instances cannot be resolved and nested lifetimes cannot be created exception on first run

### ISSUE THREAD

**Issue by KevinDockx** [IdentityServer/IdentityServer3#2248]
Hi,

one of our clients, where we're using IdentityServer, ran into a problem I haven't seen before.  

At the start of the day, after a night of inactivity (we're still in test phase), the very first request for a token fails.  Looking at the Stacktrace, this seems to be an Autofac issue.

```

Instances cannot be resolved and nested lifetimes cannot 
be created from this LifetimeScope as it has already been disposed.

Description: An unhandled exception occurred during the execution of
 the current web request. Please review the stack trace for more 
 information about the error and where it originated in the code. 

Exception Details: System.ObjectDisposedException: Instances cannot 
be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.

Source Error: 
An unhandled exception was generated during the execution of the current web request. 
Information regarding the origin and location of the exception can be identified 
using the exception stack trace below.

Stack Trace: 
[ObjectDisposedException: Instances cannot be resolved and nested lifetimes 
cannot be created from this LifetimeScope as it has already been disposed.] 

Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag, Action`1 configurationAction)
 in c:\projects\github\identity\IdSrv3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:0 
 Owin.<<UseAutofacMiddleware>b__0>d__7.MoveNext() in 
 c:\projects\github\identity\IdSrv3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:64 
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84 
 Owin.<<ConfigureIdentityServerBaseUrl>b__0>d__3.MoveNext() in 
 c:\projects\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureIdentityServerBaseUrlExtension.cs:43 
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84 
 Owin.<<ConfigureRequestId>b__0>d__2.MoveNext() in 
 c:\projects\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\AppBuilderExtensions\ConfigureRequestIdExtension.cs:37 
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84 
 IdentityServer3.Core.Configuration.Hosting.<Invoke>d__0.MoveNext() in 
 c:\projects\github\identity\IdSrv3\IdentityServer3\source\Core\Configuration\Hosting\RequireSslMiddleware.cs:48 
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84 
 Microsoft.Owin.Mapping.<Invoke>d__0.MoveNext() +777 
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
  Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +291 
  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144 
  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +293 
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32 
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +208
    System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +434 
    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288 

```

As far as I know, there's no way to control this from IdSrv as that's locked by design?  Is there any way we could fix this, or anything you know that causes this & we can look into?

For reference, a log trace (the first part is the failed first request which gets us previously described exception.  The next part is another request where it does work, and so do all the requests following this):

```
---- first request - fails -

2015-11-27 16:30:53.312 +01:00 [Debug] Creating access token
2015-11-27 16:30:53.312 +01:00 [Debug] Creating JWT access token
2015-11-27 16:30:53.312 +01:00 [Debug] Creating identity token
w3wp.exe Information: 0 : 2015-11-27 16:30:53.312 +01:00 [Information] Getting claims for identity token for subject: 82000000000
2015-11-27 16:30:53.312 +01:00 [Debug] Creating JWT identity token
w3wp.exe Information: 0 : 2015-11-27 16:30:53.328 +01:00 [Information] End authorize request
w3wp.exe Information: 0 : 2015-11-27 16:30:53.328 +01:00 [Information] Redirecting to: https://cozomobileapp/redirect

---- example of another request - works -

w3wp.exe Warning: 0 : 2015-11-30 10:47:59.531 +01:00 [Warning] AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:47:59.640 +01:00 [Warning] TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:47:59.640 +01:00 [Warning] ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:47:59.640 +01:00 [Warning] RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:48:12.375 +01:00 [Warning] AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:48:12.406 +01:00 [Warning] TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:48:12.406 +01:00 [Warning] ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:48:12.406 +01:00 [Warning] RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 2015-11-30 10:48:14.421 +01:00 [Information] Start end session request
w3wp.exe Information: 0 : 2015-11-30 10:48:14.453 +01:00 [Information] Start end session request validation
w3wp.exe Information: 0 : 2015-11-30 10:48:15.296 +01:00 [Information] "End session request validation success"
"{
  \"SubjectId\": \"unknown\",
  \"Raw\": {}
}"
w3wp.exe Information: 0 : 2015-11-30 10:48:15.296 +01:00 [Information] End end session request
w3wp.exe Information: 0 : 2015-11-30 10:48:15.312 +01:00 [Information] Redirecting to logout page
2015-11-30 10:48:15.562 +01:00 [Debug] Protecting message: "{\"Created\":635844736952968750}"
w3wp.exe Warning: 0 : 2015-11-30 10:48:27.203 +01:00 [Warning] AuthorizationCodeStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:48:27.203 +01:00 [Warning] TokenHandleStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:48:27.203 +01:00 [Warning] ConsentStore not configured - falling back to InMemory
w3wp.exe Warning: 0 : 2015-11-30 10:48:27.203 +01:00 [Warning] RefreshTokenStore not configured - falling back to InMemory
w3wp.exe Information: 0 : 2015-11-30 10:48:29.234 +01:00 [Information] Start authorize request
w3wp.exe Information: 0 : 2015-11-30 10:48:29.265 +01:00 [Information] Start authorize request protocol validation
w3wp.exe Information: 0 : 2015-11-30 10:48:29.640 +01:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"cozomobileimplicit\",
  \"ClientName\": \"CoZo Mobile (Implicit)\",
  \"RedirectUri\": \"https://cozomobileapp/redirect\",
  \"AllowedRedirectUris\": [
    \"https://cozomobileapp/redirect\"
  ],
  \"SubjectId\": \"unknown\",
  \"ResponseType\": \"id_token token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid cozomobileapi profile roles insznumber\",
  \"Nonce\": \"7e75946a-cd89-4e12-b8e0-888f6f05f0cd635844772620079890\",
  \"Raw\": {
    \"client_id\": \"cozomobileimplicit\",
    \"response_type\": \"id_token token\",
    \"scope\": \"openid cozomobileapi profile roles insznumber\",
    \"redirect_uri\": \"https://cozomobileapp/redirect\",
    \"nonce\": \"7e75946a-cd89-4e12-b8e0-888f6f05f0cd635844772620079890\"
  }
}"
w3wp.exe Information: 0 : 2015-11-30 10:48:29.656 +01:00 [Information] User is not authenticated. Redirecting to login.
w3wp.exe Information: 0 : 2015-11-30 10:48:29.718 +01:00 [Information] End authorize request
w3wp.exe Information: 0 : 2015-11-30 10:48:29.718 +01:00 [Information] Redirecting to login page
2015-11-30 10:48:29.750 +01:00 [Debug] Protecting message: "{\"ReturnUrl\":\"https://servicestest.cozo.be/identityservertest/identity/connect/authorize?client_id=cozomobileimplicit&response_type=id_token%20token&scope=openid%20cozomobileapi%20profile%20roles%20insznumber&redirect_uri=https%3A%2F%2Fcozomobileapp%2Fredirect&nonce=7e75946a-cd89-4e12-b8e0-888f6f05f0cd635844772620079890\",\"ClientId\":\"cozomobileimplicit\",\"AcrValues\":[],\"Created\":635844737090937500}"
w3wp.exe Information: 0 : 2015-11-30 10:48:30.015 +01:00 [Information] Login page requested
2015-11-30 10:48:30.046 +01:00 [Debug] signin message passed to login: "{
  \"ReturnUrl\": \"https://servicestest.cozo.be/identityservertest/identity/connect/authorize?client_id=cozomobileimplicit&response_type=id_token%20token&scope=openid%20cozomobileapi%20profile%20roles%20insznumber&redirect_uri=https%3A%2F%2Fcozomobileapp%2Fredirect&nonce=7e75946a-cd89-4e12-b8e0-888f6f05f0cd635844772620079890\",
  \"ClientId\": \"cozomobileimplicit\",
  \"IdP\": null,
  \"Tenant\": null,
  \"LoginHint\": null,
  \"DisplayMode\": null,
  \"UiLocales\": null,
  \"AcrValues\": [],
  \"Created\": 635844737090937500
}"
w3wp.exe Information: 0 : 2015-11-30 10:48:31.343 +01:00 [Information] user service returned a login result
w3wp.exe Information: 0 : 2015-11-30 10:48:31.375 +01:00 [Information] Calling PostAuthenticateAsync on the user service
w3wp.exe Information: 0 : 2015-11-30 10:48:31.390 +01:00 [Information] issuing primary signin cookie
w3wp.exe Information: 0 : 2015-11-30 10:48:31.421 +01:00 [Information] redirecting to: https://servicestest.cozo.be/identityservertest/identity/connect/authorize?client_id=cozomobileimplicit&response_type=id_token token&scope=openid cozomobileapi profile roles insznumber&redirect_uri=https:%2F%2Fcozomobileapp%2Fredirect&nonce=7e75946a-cd89-4e12-b8e0-888f6f05f0cd635844772620079890
w3wp.exe Information: 0 : 2015-11-30 10:48:31.656 +01:00 [Information] Start authorize request
w3wp.exe Information: 0 : 2015-11-30 10:48:31.656 +01:00 [Information] Start authorize request protocol validation
w3wp.exe Information: 0 : 2015-11-30 10:48:31.656 +01:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"cozomobileimplicit\",
  \"ClientName\": \"CoZo Mobile (Implicit)\",
  \"RedirectUri\": \"https://cozomobileapp/redirect\",
  \"AllowedRedirectUris\": [
    \"https://cozomobileapp/redirect\"
  ],
  \"SubjectId\": \"82000000000\",
  \"ResponseType\": \"id_token token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid cozomobileapi profile roles insznumber\",
  \"Nonce\": \"7e75946a-cd89-4e12-b8e0-888f6f05f0cd635844772620079890\",
  \"SessionId\": \"17325a14611abed9afea34bac78e3463\",
  \"Raw\": {
    \"client_id\": \"cozomobileimplicit\",
    \"response_type\": \"id_token token\",
    \"scope\": \"openid cozomobileapi profile roles insznumber\",
    \"redirect_uri\": \"https://cozomobileapp/redirect\",
    \"nonce\": \"7e75946a-cd89-4e12-b8e0-888f6f05f0cd635844772620079890\"
  }
}"
w3wp.exe Information: 0 : 2015-11-30 10:48:31.734 +01:00 [Information] Creating Implicit Flow response.
2015-11-30 10:48:31.734 +01:00 [Debug] Creating access token
2015-11-30 10:48:31.781 +01:00 [Debug] Creating JWT access token
2015-11-30 10:48:31.921 +01:00 [Debug] Creating identity token
w3wp.exe Information: 0 : 2015-11-30 10:48:31.937 +01:00 [Information] Getting claims for identity token for subject: 82000000000
2015-11-30 10:48:31.937 +01:00 [Debug] Creating JWT identity token
w3wp.exe Information: 0 : 2015-11-30 10:48:31.968 +01:00 [Information] End authorize request
w3wp.exe Information: 0 : 2015-11-30 10:48:31.984 +01:00 [Information] Redirecting to: https://cozomobileapp/redirect
```

**Comment by KevinDockx** [comment]
A bit more info on this: this happens when hosting on IIS 7.5 (W2K8R2).  I haven't yet seen this when hosting on Azure (in always on mode).  Could it be related to that?  Any ideas are welcome... :)

**Comment by leastprivilege** [comment]
sorry - no idea.

**Comment by leastprivilege** [comment]
any progress? closing. feel free to re-open if needed.

**Comment by rvanoord** [comment]
We experience a similar problem running Identity Server 3 on Azure.

Occasionally we get the following error:
`
System.ObjectDisposedException: Instances cannot be resolved and nested lifetimes cannot be created from this LifetimeScope as it has already been disposed.
at Autofac.Core.Lifetime.LifetimeScope.CheckNotDisposed()
at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag, Action`1 configurationAction)
at Autofac.Core.Container.BeginLifetimeScope(Object tag, Action`1 configurationAction)
at Owin.OwinExtensions.<>c__DisplayClass0_0.<<UseAutofacMiddleware>b__0>d.MoveNext() in C:\Users\rvanoord\Documents\Development\AppHub\**IdentityServer\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 64**
`

When this occurs, the authentication server becomes completely unavailable.

**Comment by leastprivilege** [comment]
You seem to have compiled idsrv yourself - why?

**Comment by rvanoord** [comment]
Really just to be able to understand how my store plugins are used and
called as well as debugging.

**Comment by normanhh3** [comment]
Did anyone find a resolution for this issue?

**Comment by huysentruitw** [comment]
Can be related: https://github.com/autofac/Autofac.WebApi/issues/18
