### ISSUE TITLE
2.2.2 breaks TokenValidator

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer3#2261]
...removing 

`JsonExtensions.Deserializer = JsonConvert.DeserializeObject;``

in `DefaultTokenSigningService`

fixes it. investigating.

**Comment by cogwire** [comment]
Any news on this one? I'm eager to get the fix for #2253 but this one is a blocker.

**Comment by leastprivilege** [comment]
working on it.

**Comment by leastprivilege** [comment]
Could you try 

IdentityServer3.2.2.3-build00325.nupkg

from our dev feed and tell me if this fixes the problems?

**Comment by snothub** [comment]
It fixes this but reintroduces #2253

**Comment by leastprivilege** [comment]
I can't believe that - because I did an unrelated change here only.

**Comment by leastprivilege** [comment]
check the commits.

**Comment by snothub** [comment]
I don't know what to tell you

Here's the stack, testing with parallel concurrent requests to accesstokenvalidation endpoint
```
"System.NotSupportedException: A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.\r\n
   at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()
   at System.Data.Entity.Core.Objects.ObjectQuery`1.System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>.GetAsyncEnumerator()
   at System.Data.Entity.Infrastructure.IDbAsyncEnumerableExtensions.<SingleOrDefaultAsync>d__38`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
         
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at IdentityServer3.EntityFramework.ClientStore.<FindClientByIdAsync>d__2.MoveNext()
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Services.Default.DefaultCustomTokenValidator.<ValidateAccessTokenAsync>d__4.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Services\\Default\\DefaultCustomTokenValidator.cs:line 103
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Confirmit.Identity.Service.Services.TokenValidator.<ValidateAccessTokenAsync>d__0.MoveNext() in c:\\Dev\\Auth\\Confirmit.Identity\\Confirmit.Identity.Service\\Services\\TokenValidator.cs:line 22
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at IdentityServer3.Core.Validation.TokenValidator.<ValidateAccessTokenAsync>d__e.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Validation\\TokenValidator.cs:line 210
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Endpoints.AccessTokenValidationController.<ProcessRequest>d__9.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Endpoints\\Connect\\AccessTokenValidationController.cs:line 90
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Endpoints.AccessTokenValidationController.<Get>d__0.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Endpoints\\Connect\\AccessTokenValidationController.cs:line 62
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http868615.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0
   
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\\projects\\thinktecture\\source\\Core\\Configuration\\AuthenticationTicketModel.cs:line 0"
```

**Comment by AnEmptyReece** [comment]
#2253 resolves a case of parallel operations on a DbContext for a specific case (as part of the EndSession callback). That's not to say there aren't similar issues elsewhere, but looking at the call stack it's not the same issue.

I've just tested IdentityServer3.2.2.3-build00325 and it resolves this issue and it hasn't re-introduced #2253 for me.

**Comment by snothub** [comment]
Then I'll correct myself in considering #2055 and #2253 as the same, which it clearly wasn't. Former still an issue.

**Comment by leastprivilege** [comment]
OK - gonna push 2.2.3 since this is a problem for a lot of common use cases.

**Comment by leastprivilege** [comment]
I am still not quite what the real problem is with the token validator - but I will investigate after.

**Comment by leastprivilege** [comment]
done

**Comment by snothub** [comment]
I hope I can direct your attention to #2055 (perhaps what you meant two comments ago, but not sure).
