### ISSUE TITLE
AutoMapper issue missing type config

### ISSUE THREAD

**Issue by martinlevington** [IdentityServer/IdentityServer3#2529]
Server works ok but when asking for a new token this happens:-

2016-02-04 17:00:08.837 +00:00 [Error] Exception accessing: /core/connect/authorize
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
Client -> Client
IdentityServer3.EntityFramework.Entities.Client -> IdentityServer3.Core.Models.Client

Destination path:
Client

Source value:
System.Data.Entity.DynamicProxies.Client_963A28B8041D113E74422A64B1B1E6D0EC7FD793894BA39850CE92FB2730CD73
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
   at AutoMapper.MappingEngine.MapCore(Object source, Type sourceType, Type destinationType, MappingOperationOptions options)
   at AutoMapper.MappingEngine.Map(Object source, Type sourceType, Type destinationType, Action`1 opts)
   at AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source)

**Comment by brockallen** [comment]
Sounds like this is a dup of this: https://github.com/IdentityServer/IdentityServer3.EntityFramework/issues/88

Also, I think you're posting in the wrong repo.

**Comment by martinlevington** [comment]
Yes, sorry about that, took a bit of working out what the problem was.
