### ISSUE TITLE
System.InvalidOperationException: Discovery document has no configured signing key

### ISSUE THREAD

**Issue by eaba** [IdentityServer/IdentityServer3#2660]
```
IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider Error: 0 : Discovery document has no configured signing key. aborting.
```
IdentityServer3 is being hosted on Free Azure Website and I can confirm that the certificate is loading
but there are no mention of the certificate in the log, like it used to be on my local machine.
Does IdentityServer3 require root/certificate authority to function properly?
Below is where I am getting this error:
```
AuthorizationCodeReceived = async n =>
                        {
                            var tokenClient = new TokenClient(WebConfigurationManager.AppSettings["LoginPoint"] + "/connect/token", "client", "secret")
                            {
                                Timeout = TimeSpan.FromSeconds(60)
                            };
                            var response = await tokenClient.RequestAuthorizationCodeAsync(n.Code, "https://site.net/");
```
When I type the discovery endpoint on the browser it displays.

**Comment by brockallen** [comment]
Sounds like you don't have access to the private key of the signing certificate.

**Comment by eaba** [comment]
Should I then Use a self-signed Certificate?
Because the current Certificate is signed by my own Certificate Authority

**Comment by brockallen** [comment]
Self-signed cert is the common thing to use for signing certs.

**Comment by eaba** [comment]
Okay.....I will give that a shot (heart beating faster)

**Comment by eaba** [comment]
So I got the error below after self-signing the signing certificate:
```
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
   (
   IsReadOnly = False,
   Count = 2,
   Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0x43DCD34545E6682B2773C4A8D1BA1EEEDBEA2995),
   Clause[1] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
   )
```

**Comment by brockallen** [comment]
Are you using the ws-fed plugin?

**Comment by eaba** [comment]
Yes, us there something I need to be aware?

**Comment by brockallen** [comment]
Sounds like you have a misconfigured WS-Fed RP -- change the cert validation to none.

**Comment by eaba** [comment]
It is now throwing this:
```
IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider Error: 0 : Error contacting discovery endpoint: System.InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'https://churchos.net/sso/.well-known/openid-configuration'. ---> System.IO.IOException: Unable to get document from: https://churchos.net/sso/.well-known/openid-configuration ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnectConfigurationRetriever.<GetAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider.<<RetrieveMetadata>b__0>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.AccessTokenValidation.AsyncHelper.RunSync[TResult](Func`1 func)
   at IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider.RetrieveMetadata()
    ProcessId=15384
    DateTime=2016-03-03T17:57:47.8148605Z

```
I have not make the changes yet?
Where can I get the cert Validation to change it?

**Comment by eaba** [comment]
It is now throwing this:
```
IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider Error: 0 : Error contacting discovery endpoint: System.InvalidOperationException: IDX10803: Unable to create to obtain configuration from: 'https://churchos.net/sso/.well-known/openid-configuration'. ---> System.IO.IOException: Unable to get document from: https://churchos.net/sso/.well-known/openid-configuration ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnectConfigurationRetriever.<GetAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider.<<RetrieveMetadata>b__0>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.AccessTokenValidation.AsyncHelper.RunSync[TResult](Func`1 func)
   at IdentityServer3.AccessTokenValidation.DiscoveryDocumentIssuerSecurityTokenProvider.RetrieveMetadata()
    ProcessId=15384
    DateTime=2016-03-03T17:57:47.8148605Z

```
I have not make the changes yet?
Where can I get the cert Validation to change it?

**Comment by eaba** [comment]
Thanks @brockallen  I eventually got it to work, below was the issue:
```
<location path="connect/token">
    <system.webServer>
      <security>
        <access sslFlags="Ssl, SslNegotiateCert" />
      </security>
    </system.webServer>
  </location>
```
