### ISSUE TITLE
Unhandled Exception: Bytes to be written to the stream exceed the Content-Length bytes size specified

### ISSUE THREAD

**Issue by dzintaras** [IdentityServer/IdentityServer3#2746]
In production (and in dev env) we have quite a lot of unhandled exceptions "System.Net.ProtocolViolationException: Bytes to be written to the stream exceed the Content-Length bytes size specified." Exception is quite clear in itself but the problem is diagnosing where it comes from so that it could be located and fixed. Stack trace does not help at all:

```
System.Net.ProtocolViolationException: Bytes to be written to the stream exceed the Content-Length bytes size specified.
   at System.Net.HttpResponseStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<SendResponseContentAsync>d__20.MoveNext() in c:\local\identity\server3\Core\source\Core\Internal\AntiXssLibrary\Encoder.cs:line 0
```

Note the start being **"c:\local\identity\server3\Core\source\Core\Internal\AntiXssLibrary\Encoder.cs:line 0"** which I don't think is the right one

We use IdentityServer v2.4.0 with .NET framework 4.6.1

Would you suggest some tips on solving this

P.S. we have some more exceptions with blame on "c:\local\identity\server3\Core\source\Core\Internal\AntiXssLibrary\Encoder.cs:line 0"

**Comment by dzintaras** [comment]
It looks like these errors are due to HEAD requests from the browsers - http://forums.asp.net/t/1982085.aspx?Bytes+to+be+written+to+the+stream+exceed+the+Content+Length+bytes+size+specified+

**Comment by brockallen** [comment]
Under what circumstances do you commonly see those HEAD requests?

**Comment by dzintaras** [comment]
These HEAD requests are to "/sts/login?signin=<id>" urls (IdentityServer login page) with strange user agents: "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/20.0 (Chrome)" or "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0 (Chrome)". Not sure what is the purpose of those though.

**Comment by leastprivilege** [comment]
was this ever resolved?

**Comment by dzintaras** [comment]
Resolution on our side was ignoring those exceptions as there were quite a lot of them and we had no clue for the reasons

**Comment by brockallen** [comment]
Can we close this?

**Comment by dzintaras** [comment]
Taking into account that nobody else complains about that and by ignoring exceptions we did not notice problems think we can close it
