### ISSUE TITLE
UserInfo endpoint not working

### ISSUE THREAD

**Issue by vish-k** [IdentityServer/IdentityServer3#2794]
- [X ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
UserInfo endpoint (connect/userinfo) not working. Getting NullReferenceException on tokenUsageResult.Token even though the access token is valid and can be validated successfully using connect/accesstokenvalidation.

### Relevant parts of the log file
 [2016-04-15 16:34:36,899|IdentityServer3.Core.Validation.TokenValidator|S| INFO|  42|] [GetTenantDetail.21] Token validation success
{
  "ValidateLifetime": true,
  "AccessTokenType": "Reference",
  "ExpectedScope": "openid",
  "TokenHandle": "################################",
  "Claims": {
    "scope": "No_SCOPE openid offline_access",
    "token_type": "access_token",
    "expires_in": "7043",
    "client_id": "################################",
    "access_token": "{\"##########\":\"##############\",\"########\":\"######\",\"############\":\"\"}"
  }
}
 [2016-04-15 16:34:41,925|IdentityServer3.Core.Configuration.Hosting.LogProviderExceptionLogger|S|ERROR|  42|] [] Unhandled exception
 System.NullReferenceException: Object reference not set to an instance of an object.
   at IdentityServer3.Core.Endpoints.UserInfoEndpointController.<GetUserInfo>d__6.MoveNext() in c:\local\identity\server3\Core\source\Core\Endpoints\Connect\UserInfoEndpointController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http851122.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\TokenRevocationRequestValidator.cs:line 0

**Comment by leastprivilege** [comment]
version?

**Comment by vish-k** [comment]
IdentityServer3 v 2.1.1

**Comment by leastprivilege** [comment]
Please update to v2.5

—
cheers
Dominick Baier

**Comment by vish-k** [comment]
Thanks for quick response. 
No luck with updating to v2.5. The error persists.

**Comment by leastprivilege** [comment]
Can you give me a little bit more info on how to repro - why does this not happen with our userinfo sample in the samples repo?

**Comment by vish-k** [comment]
I was able to reproduce using mitreid java sample web app. Our Java app is
using mitreid openid client library which works fine with other OP/AS. I
used OIDC auth code flow.

In my identityserver3 adoption, I am bypassing local auth and using
external ws-fed STS (mostly adfs) for auth. I have custom impl of
userbaseservice for local auth(resources owner grant), isactiveasync and
externalauth (to extract claims received for ws-fed STS to add in access
token). Also custom client service for client store. Basically, I am using
Identityserver3 strictly as auth server/OP. All OAuth2 grants (auth code,
implicit, RO, saml bearer) are working fine and in OIDC I get ID token
fine. Only userinfo endpoint fails with above error.

Pls let me know if more info is needed.

On Sat, Apr 16, 2016, 9:07 AM Dominick Baier <notifications@github.com>
wrote:

> Can you give me a little bit more info on how to repro - why does this not
> happen with our userinfo sample in the samples repo?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/2794#issuecomment-210812641>
>
-- 

Regards,
   Vish

**Comment by leastprivilege** [comment]
Can you show me the stack trace again on 2.5?

— 
cheers
Dominick Baier

On 16 April 2016 at 20:20:42, vish-k (notifications@github.com) wrote:

I was able to reproduce using mitreid java sample web app. Our Java app is
using mitreid openid client library which works fine with other OP/AS. I
used OIDC auth code flow.

In my identityserver3 adoption, I am bypassing local auth and using
external ws-fed STS (mostly adfs) for auth. I have custom impl of
userbaseservice for local auth(resources owner grant), isactiveasync and
externalauth (to extract claims received for ws-fed STS to add in access
token). Also custom client service for client store. Basically, I am using
Identityserver3 strictly as auth server/OP. All OAuth2 grants (auth code,
implicit, RO, saml bearer) are working fine and in OIDC I get ID token
fine. Only userinfo endpoint fails with above error.

Pls let me know if more info is needed.

On Sat, Apr 16, 2016, 9:07 AM Dominick Baier <notifications@github.com>
wrote:

> Can you give me a little bit more info on how to repro - why does this not
> happen with our userinfo sample in the samples repo?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/IdentityServer/IdentityServer3/issues/2794#issuecomment-210812641>
>
--

Regards,
Vish

**Comment by vish-k** [comment]
Here is the exception - 
```
 [2016-04-15 21:16:21,749|IdentityServer3.Core.Configuration.Hosting.LogProviderExceptionLogger|S|ERROR|  34|] [] Unhandled exception
 System.NullReferenceException: Object reference not set to an instance of an object.
   at IdentityServer3.Core.Endpoints.UserInfoEndpointController.<GetUserInfo>d__6.MoveNext() in c:\local\identity\server3\Core\source\Core\Endpoints\Connect\UserInfoEndpointController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http902394.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext() in c:\local\identity\server3\Core\source\Core\Validation\HashedSharedSecretValidator.cs:line 0
```

**Comment by leastprivilege** [comment]
I looked at the source code - nothing stands out (if it is really line 98).

Can you debug?

**Comment by vish-k** [comment]
It is failing on following line in UserInfoEndpointController -
var subject = tokenResult.Claims.FirstOrDefault(c => c.Type == Constants.ClaimTypes.Subject).Value;

tokenResult.Claims does not have sub claim. Can you pls tell why it is missing ? "sub" claim is available in id token.

**Comment by vish-k** [comment]
Nevermind, in my CustomTokenValidator, i wasn't adding the subject claim. Once I fixed that I no longer get the exception.
Still need to figure out how to add claims to userinfo reply... currently, it returns empty reply.
