### ISSUE TITLE
Integrating ids with google idp

### ISSUE THREAD

**Issue by sudipster** [IdentityServer/IdentityServer3#2940]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I  am trying to integrate my IIS hosted ids with ext idps such as google:  
app.UseGoogleAuthentication(new GoogleOAuth2AuthenticationOptions
            {
                SignInAsAuthenticationType = signInAsType,
                AuthenticationType = "Google",
                Caption = "Sign-in with Google",
                ClientId = "xxxx.apps.googleusercontent.com",
                ClientSecret = "xxxx"
            });

However, I am getting access denied error and the logs show "The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format".  

I see the following redirects in Chrome:
https://localhost:1443/identityserver3/external?provider=Google&signin=2463080527837bbacd8e7e44a9b4cd35

https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=

https://localhost:1443/identityserver3/signin-google?state=

https://localhost:1443/identityserver3/callback?error=access_denied

Any clues as to where this error regarding handshake failure happenning?
Thanks.
### Relevant parts of the log file

```
w3wp.exe Error: 0 : 2016-05-31 17:36:03.887 -05:00 [Error] Authentication failed
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: 
The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Owin.Security.Google.GoogleOAuth2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> 
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Owin.Security.Google.GoogleOAuth2AuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
2016-05-31 17:36:03.892 -05:00 [Debug] Request, Method=GET, Url=https://localhost:1443/identityserver3/callback?error=access_denied, 
Message='https://localhost:1443/identityserver3/callback?error=access_denied'
2016-05-31 17:36:03.892 -05:00 [Debug] Message='Authentication', Operation=DefaultHttpControllerSelector.SelectController
2016-05-31 17:36:03.893 -05:00 [Debug] Message='IdentityServer3.Core.Endpoints.AuthenticationController', Operation=DefaultHttpControllerActivator.Create
2016-05-31 17:36:03.893 -05:00 [Debug] Message='IdentityServer3.Core.Endpoints.AuthenticationController', Operation=HttpControllerDescriptor.CreateController
2016-05-31 17:36:03.893 -05:00 [Debug] Message='Selected action 'LoginExternalCallback(String error)'', Operation=ApiControllerActionSelector.SelectAction
2016-05-31 17:36:03.893 -05:00 [Debug] Message='The authentication filter did not encounter an error or set a principal.', Operation=HostAuthenticationAttribute.AuthenticateAsync
2016-05-31 17:36:03.893 -05:00 [Debug] Operation=HostAuthenticationAttribute.ChallengeAsync
2016-05-31 17:36:03.893 -05:00 [Debug] Operation=PreventUnsupportedRequestMediaTypesAttribute.OnAuthorizationAsync
2016-05-31 17:36:03.893 -05:00 [Debug] Message='Parameter 'error' bound to the value 'access_denied'', Operation=ModelBinderParameterBinding.ExecuteBindingAsync
2016-05-31 17:36:03.893 -05:00 [Debug] Message='Model state is valid. Values: error=access_denied', Operation=HttpActionBinding.ExecuteBindingAsync
2016-05-31 17:36:03.893 -05:00 [Debug] Operation=SecurityHeadersAttribute.OnActionExecutingAsync
2016-05-31 17:36:03.893 -05:00 [Debug] Operation=NoCacheAttribute.OnActionExecutingAsync
w3wp.exe Information: 0 : 2016-05-31 17:36:03.897 -05:00 [Information] Callback invoked from external identity provider
w3wp.exe Error: 0 : 2016-05-31 17:36:03.897 -05:00 [Error] External identity provider returned error: "access_denied"
w3wp.exe Information: 0 : 2016-05-31 17:36:03.906 -05:00 [Information] {
  "Category": "Authentication",
  "Name": "External Login Error",
  "EventType": "Error",
  "Id": 1022,
  "Message": "access_denied",
  "Context": {
    "ActivityId": "2916db44-f5e4-400c-9a20-181dbf89a6b0",
    "TimeStamp": "2016-05-31T22:36:03.90094+00:00",
    "ProcessId": 22428,
    "MachineName": "localhost",
    "RemoteIpAddress": "000.0.0.205"
  }
}
2016-05-31 17:36:03.908 -05:00 [Debug] Message='Action returned 'IdentityServer3.Core.Results.ErrorActionResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
2016-05-31 17:36:03.909 -05:00 [Debug] Operation=ApiControllerActionInvoker.InvokeActionAsync, Status=200 (OK)
2016-05-31 17:36:03.909 -05:00 [Debug] Operation=NoCacheAttribute.OnActionExecutedAsync, Status=200 (OK)
2016-05-31 17:36:03.910 -05:00 [Debug] Operation=SecurityHeadersAttribute.OnActionExecutedAsync, Status=200 (OK)
2016-05-31 17:36:03.910 -05:00 [Debug] Operation=AuthenticationController.ExecuteAsync, Status=200 (OK)
2016-05-31 17:36:03.910 -05:00 [Debug] Operation=PassiveAuthenticationMessageHandler.SendAsync, Status=200 (OK)
2016-05-31 17:36:03.910 -05:00 [Debug] Operation=DependencyScopeHandler.SendAsync, Status=200 (OK)
2016-05-31 17:36:03.910 -05:00 [Debug] Response, Status=200 (OK), Method=GET, Url=https://wern18797.wernerds.net:1443/identityserver3/callback?error=access_denied, Message='Content-type='text/html; charset=utf-8', content-length=2341'
2016-05-31 17:36:03.910 -05:00 [Debug] Operation=AuthenticationController.Dispose
```

**Comment by leastprivilege** [comment]
my money is on a firewall blocking outgoing communication to google.

**Comment by sudipster** [comment]
Should have mentioned I am facing the above issue with iis hosted ids. May be some corp fw issue.. When I use self hosted ids or in iis express, it works without any problems.

**Comment by brockallen** [comment]
All set with this? Can we close?
