### ISSUE TITLE
System.Exception: Illegal base64url string!

### ISSUE THREAD

**Issue by AlexZeitler** [IdentityServer/IdentityServer3#3175]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I configured `IdentityServer 2.5.1` together with `IdentityServer.EntityFramework 2.5.1`.
I created a Implicit Client configuration:

```js
{
  "Id": 14,
  "ClientId": "sampleapiclient",
  "ClientName": "Sample API Client",
  "ClientUri": "http://localhost:9000",
  "Claims": [],
  "AllowedCorsOrigins": [
    {
      "Id": 3,
      "Origin": "http://localhost:9000"
    }
  ],
  "AllowedCustomGrantTypes": [],
  "IdentityProviderRestrictions": [],
  "PostLogoutRedirectUris": [
    {
      "Id": 5,
      "Uri": "http://localhost:9000/"
    }
  ],
  "RedirectUris": [
    {
      "Id": 15,
      "Uri": "http://localhost:9000/index.html"
    }
  ],
  "AllowedScopes": [
    {
      "Id": 64,
      "Scope": "openid"
    },
    {
      "Id": 65,
      "Scope": "myWebApi"
    },
    {
      "Id": 66,
      "Scope": "read"
    },
    {
      "Id": 67,
      "Scope": "write"
    },
    {
      "Id": 68,
      "Scope": "profile"
    },
    {
      "Id": 69,
      "Scope": "email"
    }
  ],
  "Enabled": true,
  "LogoUri": null,
  "RequireConsent": false,
  "AllowRememberConsent": true,
  "AllowAccessTokensViaBrowser": true,
  "Flow": 1,
  "AllowClientCredentialsOnly": false,
  "LogoutUri": null,
  "LogoutSessionRequired": true,
  "RequireSignOutPrompt": false,
  "AllowAccessToAllScopes": false,
  "IdentityTokenLifetime": 300,
  "AccessTokenLifetime": 3600,
  "AuthorizationCodeLifetime": 300,
  "AbsoluteRefreshTokenLifetime": 2592000,
  "SlidingRefreshTokenLifetime": 1296000,
  "RefreshTokenUsage": 1,
  "UpdateAccessTokenOnRefresh": false,
  "RefreshTokenExpiration": 1,
  "AccessTokenType": 0,
  "EnableLocalLogin": true,
  "IncludeJwtId": false,
  "AlwaysSendClientClaims": false,
  "PrefixClientClaims": true,
  "AllowAccessToAllGrantTypes": false
}
```

I'm using the Implicit JS Client from here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient

The client settings in `app.js`:

```js
var settings = {
    authority: "http://localhost:3004/identity",
    client_id: "sampleapiclient",
    redirect_uri: window.location.protocol + "//" + window.location.host + "/index.html",
    post_logout_redirect_uri: window.location.protocol + "//" + window.location.host + "/index.html",

    // these two will be done dynamically from the buttons clicked, but are
    // needed if you want to use the silent_renew
    response_type: "id_token token",
    scope: "openid profile email read write",

    // silent renew will get a new access_token via an iframe 
    // just prior to the old access_token expiring (60 seconds prior)
    silent_redirect_uri: window.location.protocol + "//" + window.location.host + "/silent_renew.html",
    automaticSilentRenew: true,

    // this will allow all the OIDC protocol claims to vbe visible in the window. normally a client app 
    // wouldn't care about them or want them taking up space
    filterProtocolClaims: true,

    // this will use the user info endpoint if it's an OIDC request and there's an access_token
    loadUserInfo: true
};
```

When hitting the "Login only" button in the client, I'm redirected to IdSrv and get this error:
`There was an unexpected error`

### Relevant parts of the log file

```
2016-08-30 02:56:39 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"sampleapiclient\",
  \"ClientName\": \"Sample API Client\",
  \"RedirectUri\": \"http://localhost:9000/index.html\",
  \"AllowedRedirectUris\": [
    \"http://localhost:9000/index.html\"
  ],
  \"SubjectId\": \"unknown\",
  \"ResponseType\": \"id_token\",
  \"ResponseMode\": \"fragment\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid\",
  \"State\": \"53d9572f75a04bc7a2d2408eeb460c55\",
  \"Nonce\": \"0ca43a2b71f34dadaec44a60a997e3c1\",
  \"Raw\": {
    \"client_id\": \"sampleapiclient\",
    \"redirect_uri\": \"http://localhost:9000/index.html\",
    \"response_type\": \"id_token\",
    \"scope\": \"openid\",
    \"state\": \"53d9572f75a04bc7a2d2408eeb460c55\",
    \"nonce\": \"0ca43a2b71f34dadaec44a60a997e3c1\"
  }
}"
2016-08-30 02:56:39 [Information] User is not authenticated. Redirecting to login.
2016-08-30 02:56:39 [Information] End authorize request
2016-08-30 02:56:39 [Information] Redirecting to login page
2016-08-30 02:56:39 [Error] Unhandled exception
System.Exception: Illegal base64url string!
   at IdentityModel.Base64Url.Decode(String arg) in c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Ba
se64Url.cs:line 33
   at IdentityServer3.Core.Extensions.IDataProtectorExtensions.Unprotect(IDataProtector protector, String data, String e
ntropy) in c:\local\identity\server3\IdentityServer3\source\Core\Extensions\IDataProtectorExtensions.cs:line 52
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.Unprotect(String data, IDataProtector protector) in c:\
local\identity\server3\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 81
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.Unprotect(String data) in c:\local\identity\server3\Ide
ntityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 125
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.ReadByCookieName(String name) in c:\local\identity\serv
er3\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 171
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.GetCookieRank(String name) in c:\local\identity\server3
\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 201
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.<ClearOverflow>b__a(String name) in c:\local\identity\s
erver3\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 229
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SkipIterator>d__30`1.MoveNext()
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.ClearOverflow() in c:\local\identity\server3\IdentitySe
rver3\source\Core\Configuration\Hosting\MessageCookie.cs:line 234
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.Write(TMessage message) in c:\local\identity\server3\Id
entityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 140
   at IdentityServer3.Core.Extensions.OwinEnvironmentExtensions.CreateSignInRequest(IDictionary`2 env, SignInMessage mes
sage) in c:\local\identity\server3\IdentityServer3\source\Core\Extensions\OwinEnvironmentExtensions.cs:line 138
   at IdentityServer3.Core.Results.LoginResult.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Result
s\LoginResult.cs:line 57
   at IdentityServer3.Core.Results.LoginResult.ExecuteAsync(CancellationToken cancellationToken) in c:\local\identity\se
rver3\IdentityServer3\source\Core\Results\LoginResult.cs:line 48
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\local\identity
\server3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\s
erver3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\s
erver3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\local\identity\server3\Identity
Server3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() in c:\lo
cal\identity\server3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\
IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\Ident
ityServer3\source\Core\Validation\ScopeValidator.cs:line 0
2016-08-30 02:56:39 [Error] Exception accessing: /identity/connect/authorize
System.Exception: Illegal base64url string!
   at IdentityModel.Base64Url.Decode(String arg) in c:\local\identity\model\IdentityModel\source\IdentityModel.Shared\Ba
se64Url.cs:line 33
   at IdentityServer3.Core.Extensions.IDataProtectorExtensions.Unprotect(IDataProtector protector, String data, String e
ntropy) in c:\local\identity\server3\IdentityServer3\source\Core\Extensions\IDataProtectorExtensions.cs:line 52
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.Unprotect(String data, IDataProtector protector) in c:\
local\identity\server3\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 81
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.Unprotect(String data) in c:\local\identity\server3\Ide
ntityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 125
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.ReadByCookieName(String name) in c:\local\identity\serv
er3\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 171
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.GetCookieRank(String name) in c:\local\identity\server3
\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 201
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.<ClearOverflow>b__a(String name) in c:\local\identity\s
erver3\IdentityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 229
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SkipIterator>d__30`1.MoveNext()
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.ClearOverflow() in c:\local\identity\server3\IdentitySe
rver3\source\Core\Configuration\Hosting\MessageCookie.cs:line 234
   at IdentityServer3.Core.Configuration.Hosting.MessageCookie`1.Write(TMessage message) in c:\local\identity\server3\Id
entityServer3\source\Core\Configuration\Hosting\MessageCookie.cs:line 140
   at IdentityServer3.Core.Extensions.OwinEnvironmentExtensions.CreateSignInRequest(IDictionary`2 env, SignInMessage mes
sage) in c:\local\identity\server3\IdentityServer3\source\Core\Extensions\OwinEnvironmentExtensions.cs:line 138
   at IdentityServer3.Core.Results.LoginResult.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Result
s\LoginResult.cs:line 57
   at IdentityServer3.Core.Results.LoginResult.ExecuteAsync(CancellationToken cancellationToken) in c:\local\identity\se
rver3\IdentityServer3\source\Core\Results\LoginResult.cs:line 48
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\local\identity
\server3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\s
erver3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\serv
er3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\s
erver3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\local\identity\server3\Identity
Server3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() in c:\lo
cal\identity\server3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\
IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\Ident
ityServer3\source\Core\Validation\ScopeValidator.cs:line 0
```

**Comment by brockallen** [comment]
Is this consistently reproduceable?

**Comment by AlexZeitler** [comment]
Yes, I can delete the entire database and let it recreate from scratch. BTW I'm using it in conjunction with IdentityServer3.AspNetIdentity as well (Clients/ Scopes are handled by IdentityServer3.EntityFramework and Users / Claims are handled by IdentityServer.AspNetIdentity).

**Comment by AlexZeitler** [comment]
WRT to IdentityServer.AspNetIdentity: I can remove the bootstrapping code for it and the error still occurs.

**Comment by AlexZeitler** [comment]
Deleting the cookies resolved it.

**Comment by leastprivilege** [comment]
You don't happen to have a copy of that cookie? ;)

**Comment by AlexZeitler** [comment]
Sorry, no. But I can try to recreate it. I guess the following happened: I have been using the test client and it was configured for an IdSrv instance listing at https://sts and then I changed it to work against an IdSrv listening at http://localhost:3004.

**Comment by leastprivilege** [comment]
yeah - never mind ;)

**Comment by brockallen** [comment]
That cookie value is protected with the hosting data protection, so perhaps in your hosting changes the data protector for the different host settings refused to unprotect.

**Comment by AlexZeitler** [comment]
@brockallen Thanks. Also it is unlikely this will happen in production, do you think it is possible to get a more expressive Exception message?

**Comment by brockallen** [comment]
Yea, we discussed perhaps deleting the cookie when this happens... I'll track it here: #3177
