### ISSUE TITLE
OauthClient throwing error

### ISSUE THREAD

**Issue by webproof** [IdentityServer/IdentityServer3#3216]
- [ X] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
When I am calling the RequestResourceOwnerPasswordAsync method in the OAuthClient it throws the message below.

### Relevant parts of the log file

```
<log goes here>
An error occurred while sending the request.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityModel.Client.OAuth2Client.<RequestAsync>d__a.MoveNext() in c:\etc\Dropbox\thinktecture\IdentityModel\source\Client.Shared\OAuth2Client.cs:line 277
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WebProof.Auth.IdentityTests.IdServerTests.<ShouldTestPassword>d__0.MoveNext() in C:\Geirr\Geirr\WebProof2\Tests\WebProof.Auth.IdentityTests\IdServerTests.cs:line 13
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at Xunit.Sdk.AsyncTestSyncContext.<>c__DisplayClass7_0.<Post>b__1(Object _) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\AsyncTestSyncContext.cs:line 75

System.Net.WebException
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

System.Security.Authentication.AuthenticationException
The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)

**Comment by leastprivilege** [comment]
"The remote certificate is invalid according to the validation procedure."

SSL/TLS problem.

To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
