### ISSUE TITLE
Error posting back to Oidc client

### ISSUE THREAD

**Issue by vidarkongsli** [IdentityServer/IdentityServer3#3270]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I have set up an Oidc client app (asp.net mvc) but I get an error message when the user is authenticated and is about to be sent back to the client. As far as I can trace this error, it seems that the resource `AuthorizeResponseView` is not present, which seems very strange. Any idea why this happens?

### Relevant parts of the log file

```
iisexpress.exe Information: 0 : 2016-10-03 14:34:30.967 +02:00 [Information] End authorize request
2016-10-03 14:34:30.974 +02:00 [Debug] [2016-10-03T12:34:30.9673181Z] Level=Info, Kind=End, Category='System.Web.Http.Action', Id=80006edf-0000-7800-b63f-84710c7967bb, Message='Action returned 'IdentityServer3.Core.Results.AuthorizeFormPostResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
iisexpress.exe Information: 0 : 2016-10-03 14:34:30.979 +02:00 [Information] Posting to https://localhost:44323
2016-10-03 14:34:30.979 +02:00 [Debug] Using DefaultViewService to render authorization response HTML
2016-10-03 14:34:31.119 +02:00 [Debug] [2016-10-03T12:34:31.0953309Z] Level=Error, Kind=End, Category='System.Web.Http.Action', Id=80006edf-0000-7800-b63f-84710c7967bb, Operation=ApiControllerActionInvoker.InvokeActionAsync, Exception=System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at IdentityServer.Web.AssetManager.LoadResourceString(String name) in C:\dev\tfs-002\Identity\Dev\IdentityServer.Web\AssetManager.cs:line 85
   at IdentityServer.Web.AssetManager.LoadPage(String pageName) in C:\dev\tfs-002\Identity\Dev\IdentityServer.Web\AssetManager.cs:line 28
   at IdentityServer.Web.AssetManager.LoadLayoutWithPage(String pageName) in C:\dev\tfs-002\Identity\Dev\IdentityServer.Web\AssetManager.cs:line 44
   at IdentityServer.Web.EmbeddedAssetsViewLoader.LoadAsync(String name) in C:\dev\tfs-002\Identity\Dev\IdentityServer.Web\EmbeddedAssetsViewLoader.cs:line 18
   at IdentityServer.Web.FileSystemWithEmbeddedFallbackViewLoader.<LoadAsync>d__5.MoveNext() in C:\dev\tfs-002\Identity\Dev\IdentityServer.Web\FileSystemWithEmbeddedFallbackViewLoader.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdentityServer3.Core.Services.Default.CachingLoader.<LoadAsync>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\DefaultViewService\CachingLoader.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdentityServer3.Core.Services.Default.DefaultViewService.<AuthorizeResponse>d__1.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\DefaultViewService\DefaultViewService.cs:line 191
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at IdentityServer3.Core.Results.HtmlStreamActionResult.<Render>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Results\HtmlStreamActionResult.cs:line 37

```
Thanks

**Comment by brockallen** [comment]
Are you building IdentityServer yourself (meaning from your own clone of the code)?

**Comment by vidarkongsli** [comment]
Nope, I am using the Nuget distro version 2.5.4.

**Comment by brockallen** [comment]
Ok, these lines `C:\dev\tfs-002\Identity\Dev\IdentityServer.Web\` looked like maybe you had done your own build and if you didn't use our NuGet or build script, then it might explain why you don't have the embedded assets.

**Comment by vidarkongsli** [comment]
No, that's the host project. :)

**Comment by brockallen** [comment]
This happens consistently?

**Comment by vidarkongsli** [comment]
Yes, I am developing a new IdSrv solution for a customer, and this is my `localhost` test rig. I am stuck on this problem, it happens every time I try to log in. I haven't tried it on several users/clients/etc. though.

**Comment by brockallen** [comment]
So something sounds wrong -- the stream being read is an embedded resource and for some reason it's `null` which tells me either there's a bug where the wrong name is being used to load it, or it's just not in the DLL. More debugging is needed. I'll try to verify that the local build is working properly.

**Comment by vidarkongsli** [comment]
It's strange. According to the MANIFEST of `IdentityServer3.Core.dll`, the embedded resource is there:
> .mresource public IdentityServer3.Core.Services.DefaultViewService.PageAssets.authorizeresponse.html
> {
>   // Offset: 0x0002E523 Length: 0x000000F5
> }

Looking at the code, it is even stranger that the stream should be `null`, since there is a null check surrounding the call:
> var assembly = typeof(AssetManager).Assembly;
> var s = assembly.GetManifestResourceStream(name);
> if (s != null)
> {
>     using (var sr = new StreamReader(s)) // BANG!
>     {
>         ...
>     }
> }

**Comment by vidarkongsli** [comment]
You were on to something eariler, @brockallen. I was mistaken. It seems that the solution I am working on had made its own `AssetManager` for some reason. This is clearly a local problem in the solution. Sorry for wasting your time.
