### ISSUE TITLE
invalid bearer token received issue on DMZ server

### ISSUE THREAD

**Issue by sapandeepprimecaretech** [IdentityServer/IdentityServer3#3311]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)
### Question / Issue

We have Identitryserver3 and asp.net web api2/Kendo ui website hosted on DMZ server with valid certificates . We don't have dns entries updated from client yet. so we have done internal domain zoning to test the website. when we run the website its letting user enter login credentials , but then identity server gives following error in OwinTrace.log file.  it doesn't call website's URL but always shows server's IP address and not letting client login even with valid credentials. Please advise. 

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.AccessTokenValidation.ValidationEndpointTokenProvider.<ReceiveAsync>d__1.MoveNext() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\ValidationEndpointTokenProvider.cs:line 88
Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Warning: 0 : invalid bearer token received
IdentityServer3.AccessTokenValidation.ValidationEndpointTokenProvider Error: 0 : Exception while contacting token validation endpoint: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 209.X.XXX:443
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.AccessTokenValidation.ValidationEndpointTokenProvider.<ReceiveAsync>d__1.MoveNext() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\ValidationEndpointTokenProvider.cs:line 88
Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Warning: 0 : invalid bearer token received
### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
Here's your issue:

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 209.X.XXX:443

**Comment by sapandeepprimecaretech** [comment]
I know , but how to resolve it and why its coming . both website and Identity server are on same server. Even website is sending request to IDentityserver without any issue. both have same IP address and port 443. but still its giving that error.

**Comment by brockallen** [comment]
Outgoing firewall issue?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
