### ISSUE TITLE
Error while rendering login page

### ISSUE THREAD

**Issue by NovakSavic** [IdentityServer/IdentityServer3#3358]
- [x ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
From today, I get errors in the log like below, but my custom login page renders without any problem.
What could be the reason for this errors?

### Relevant parts of the log file

```
2016-11-09 08:53:57,345 [8] INFO  IdentityServer3.Core.Endpoints.AuthenticationController - rendering login page
2016-11-09 08:53:57,384 [10] ERROR IdentityServer3.Core.Configuration.Hosting.LogProviderExceptionLogger - Unhandled exception
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException ---> System.Net.HttpListenerException: The I/O operation has been aborted because of either a thread exit or an application request
   at System.Net.HttpResponseStream.EndWrite(IAsyncResult asyncResult)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.EndWrite(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferWrittenCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<SendResponseContentAsync>d__20.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Validation\ScopeValidator.cs:line 0
```

**Comment by brockallen** [comment]
Related: https://github.com/IdentityServer/IdentityServer3/issues/3253

**Comment by brockallen** [comment]
Closing/dup
