### ISSUE TITLE
Custom Event Service Event<T> serializing

### ISSUE THREAD

**Issue by mainettis** [IdentityServer/IdentityServer3#3588]
- [ x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question

Is there something that I need to add somewhere to approximate the output of the default service when serialized?

I've been trying to implement my own event service for logging inheriting IEventService. And, I keep running into a "Self reference loop" when claims are returned as the evt is being converted to Json.

I looked through idsrv3 source code and replaced what I wrote with parts of the [LogSerializer ](https://github.com/IdentityServer/IdentityServer3/blob/93bc6bc9b536146b9e3fa0bed21d77283d07f788/source/Core/Logging/LogSerializer.cs) to help me trouble shoot:
```
public Task RaiseAsync<T>(Event<T> evt)
        {
            var jsonSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                Formatting = Formatting.Indented
            };
           jsonSettings.Converters.Add(new StringEnumConverter());
           Log.Information(JsonConvert.SerializeObject(evt, jsonSettings));
            

           return Task.FromResult(0);
        }
```

And still get this issue.

I tried adding `ReferenceLoopHandling.Ignore` to the JsonSerializerSettings and noticed the TokenService event log looks very different than what I get when I use the default event service.

### Relevant parts of the log file
**Error**
```
2017-03-23 08:46:38.367 -05:00 [Information] Creating Hybrid Flow response.
2017-03-23 08:46:40.617 -05:00 [Error] Unhandled exception
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected with type 'System.Security.Claims.Claim'. Path 'DetailsFunc.target0.code.Subject.Claims[0].Subject.Claims'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Pds.Id.Services.LogEventService.RaiseAsync[T](Event`1 evt) in C:\repo\Services\WebService\Pds.Elmo\Pds.Id\Services\LogEventService.cs:line 115
   at IdentityServer3.Core.Services.Default.EventServiceDecorator.RaiseAsync[T](Event`1 evt) in c:\local\identity\server3\IdentityServer3\source\Core\Services\Default\EventServiceDecorator.cs:line 49
   at IdentityServer3.Core.Extensions.IEventServiceExtensions.<RaiseEventAsync>d__b8`1.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Extensions\IEventServiceExtensions.cs:line 663
--- End of stack trace from previous location where exception was thrown ---
```

**Ignoring Reference Loop**
```
2017-03-23 08:21:09.914 -05:00 [Information] Creating Hybrid Flow response.
2017-03-23 08:21:12.028 -05:00 [Information] {
  "DetailsFunc": {
    "Delegate": {},
    "target0": {
      "id": "cb538e08666e8411d2d272da234a9c25",
      "code": {
        "CreationTime": "2017-03-23T13:21:09.9150422+00:00",
        "Client": {
          "Enabled": true,
          "ClientId": "test",
          "ClientSecrets": [],
          "ClientName": "Test this",
          "RequireConsent": false,
          "AllowRememberConsent": true,
          "Flow": "Hybrid",
          "AllowClientCredentialsOnly": false,
          "RedirectUris": [
            "https://localhost:44318/"
          ],
          "PostLogoutRedirectUris": [
            "https://localhost:44318/"
          ],
          "LogoutSessionRequired": true,
          "RequireSignOutPrompt": false,
          "AllowAccessToAllScopes": true,
          "AllowedScopes": [],
          "IdentityTokenLifetime": 10,
          "AccessTokenLifetime": 60,
          "AuthorizationCodeLifetime": 300,
          "AbsoluteRefreshTokenLifetime": 2592000,
          "SlidingRefreshTokenLifetime": 1296000,
          "RefreshTokenUsage": "OneTimeOnly",
          "UpdateAccessTokenClaimsOnRefresh": false,
          "RefreshTokenExpiration": "Absolute",
          "AccessTokenType": "Jwt",
          "EnableLocalLogin": true,
          "IdentityProviderRestrictions": [],
          "IncludeJwtId": false,
          "Claims": [],
          "AlwaysSendClientClaims": false,
          "PrefixClientClaims": true,
          "AllowAccessToAllCustomGrantTypes": false,
          "AllowedCustomGrantTypes": [],
          "AllowedCorsOrigins": [],
          "AllowAccessTokensViaBrowser": true
        },
        "Subject": {
          "Claims": [
            {
              "Issuer": "LOCAL AUTHORITY",
              "OriginalIssuer": "LOCAL AUTHORITY",
              "Properties": {},
              "Subject": {
                "AuthenticationType": "idsrv",
                "IsAuthenticated": true,
                "Claims": [
..... 
"method0": {
      "Name": "<RaiseAuthorizationCodeIssuedEventAsync>b__56",
      "AssemblyName": "IdentityServer3, Version=2.5.0.0, Culture=neutral, PublicKeyToken=null",
      "ClassName": "IdentityServer3.Core.Extensions.IEventServiceExtensions+<>c__DisplayClass57",
      "Signature": "IdentityServer3.Core.Events.AuthorizationCodeDetails <RaiseAuthorizationCodeIssuedEventAsync>b__56()",
      "Signature2": "IdentityServer3.Core.Events.AuthorizationCodeDetails <RaiseAuthorizationCodeIssuedEventAsync>b__56()",
      "MemberType": 8,
      "GenericArguments": null
    }
  },
  "Category": "TokenService",
  "Name": "Authorization code issued",
  "EventType": "Information",
  "Id": 2010,
  "Details": {
    "HandleId": "cb538e08666e8411d2d272da234a9c25",
    "RedirectUri": "https://localhost:44318/",
    "SubjectId": "####",
    "ClientId": "test",
    "Scopes": [
      "openid",
      "profile",
      "roles",
      "offline_access"
    ],
    "Lifetime": 300
  },
  "Context": {
    "ActivityId": "80001554-0004-ef00-b63f-84710c7967bb",
    "TimeStamp": "2017-03-23T13:21:09.9200422+00:00",
    "ProcessId": 14892,
    "MachineName": "####",
    "RemoteIpAddress": "::1",
    "SubjectId": "####"
  }
```
**Using default log**
```
2017-03-23 07:54:00.367 -05:00 [Information] Creating Hybrid Flow response.
2017-03-23 07:54:00.379 -05:00 [Information] {
  "Category": "TokenService",
  "Name": "Authorization code issued",
  "EventType": "Information",
  "Id": 2010,
  "Details": {
    "HandleId": "1906666f10af102bcb6da32b3bbce8d5",
    "RedirectUri": "https://localhost:44318/",
    "SubjectId": "####",
    "ClientId": "local_test",
    "Scopes": [
      "openid",
      "profile",
      "roles",
      "offline_access"
    ],
    "Lifetime": 300
  },
  "Context": {
    "ActivityId": "80000987-0002-ef00-b63f-84710c7967bb",
    "TimeStamp": "2017-03-23T12:54:00.3731447+00:00",
    "ProcessId": 27368,
    "MachineName": "####",
    "RemoteIpAddress": "::1",
    "SubjectId": "####"
  }
}
```

**Comment by brockallen** [comment]
You might just need to hand code some of these pieces...  here's our seq sample: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/SelfHost%20SeqEvents/SelfHost/SeqEventService.cs
