### ISSUE TITLE
IDServer 3 & ADFS

### ISSUE THREAD

**Issue by FredBesterwitch** [IdentityServer/IdentityServer3#3607]
- [ ] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Guys,
I'm getting this error in my API while trying to access my API . Can you please help
The auth Server is ADFS

Here is my code..

`
API startup.cs
 JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "MyAuthServer",
                RequiredScopes = new[] { "openid" },
                ClientId = "MYAPI",
                ClientSecret = "clientsecret"
            });

calling client

  TokenClient _tokenClient = new TokenClient("MyAuthServer/oauth2/token/",
                        "MYAPI",
                        "clientsecret");
            

            var response = await _tokenClient.RequestClientCredentialsAsync();

     var client = new HttpClient();
        
            client.SetBearerToken(response.AccessToken);
            client.DefaultRequestHeaders.Accept.Clear();
            client.MaxResponseContentBufferSize = 256000;

            try
            {
                string url = "http://localhost:5000/StoreFront/GetSKUInfo/010180";
                var uri = new Uri(string.Format(url, string.Empty));
// This call to the API where I get an Error 500
                var apiresponse = await client.GetAsync(uri);
`
### Relevant parts of the log file

Error Log 
Authentication failed
 (3b5ca34b)
System.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10505: Unable to validate signature. The 'Delegate' specified on TokenValidationParameters, returned a null SecurityKey.
SecurityKeyIdentifier: 'SecurityKeyIdentifier
    (
    IsReadOnly = False,
    Count = 1,
    Clause[0] = X509ThumbprintKeyIdentifierClause(Hash = 0x97F3995268AD145BA0FEA813E1A06BBE7CB19BDE)
    )
'
Token: '{"typ":"JWT","alg":"RS256","x5t":"l_OZUmitFFug_qgT4aBrvnyxm94"}.{"aud":"urn:microsoft:userinfo","iss":"MyAuthServer/services/trust","iat":1490855179,"exp":1490858779,"apptype":"Confidential","appid":"MYAPI","authmethod":"http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password","auth_time":"2017-03-30T06:26:19.997Z","ver":"1.0"}'.
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
2017-03-30T17:26:30.1538651+11:00 0HL3N6FOOPNCU [INF] Authorization failed for user: null. (a4ab1676)
2017-03-30T17:26:30.1548687+11:00 0HL3N6FOOPNCU [WRN] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'. (8b6446cb)
2017-03-30T17:26:30.1558711+11:00 0HL3N6FOOPNCU [INF] Executing ChallengeResult with authentication schemes ([]). (f3dca807)
2017-03-30T17:26:30.1568737+11:00 0HL3N6FOOPNCU [ERR] No authentication handler is configured to handle the scheme: Automatic (d05b54cb)
2017-03-30T17:26:30.1578764+11:00 0HL3N6FOOPNCU [INF] Request finished in 18.24ms 500 application/json (15c52c40)
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
