### ISSUE TITLE
Error Creating JWT Access Token

### ISSUE THREAD

**Issue by scsloan** [IdentityServer/IdentityServer3#3650]
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
We recently switch certification authorities and am getting an error when trying to log into through our applications. 

Searching through the issues, I found issue #2859 and followed Dominick's link. But it did not fix the problem.

Looking for some guidance. 

### Relevant parts of the log file

```
2017-04-21 08:59:02.019 -05:00 [Debug] Creating access token
2017-04-21 08:59:03.319 -05:00 [Debug] Creating JWT access token
2017-04-21 08:59:03.397 -05:00 [Debug] [2017-04-21T13:59:03.3975443Z] Level=Error, Kind=End, Category='System.Web.Http.Action', Id=d7168bf2-ee96-446b-9af3-2f0a44f4914c, Operation=ReflectedHttpActionDescriptor.ExecuteAsync, Exception=System.InvalidOperationException: IDX10614: AsymmetricSecurityKey.GetSignatureFormater( 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256' ) threw an exception.
Key: 'System.IdentityModel.Tokens.X509AsymmetricSecurityKey'
SignatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256', check to make sure the SignatureAlgorithm is supported.
Exception:'System.Security.Cryptography.CryptographicException: Invalid provider type specified.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetSignatureFormatter(String algorithm)
   at System.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(AsymmetricSecurityKey key, String algorithm, Boolean willCreateSignatures) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\AsymmetricSignatureProvider.cs:line 147'.
If you only need to verify signatures the parameter 'willBeUseForSigning' should be false if the private key is not be available. ---> System.Security.Cryptography.CryptographicException: Invalid provider type specified.


```

**Comment by leastprivilege** [comment]
That's a Microsoft exception - open an issue here:

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues

**Comment by scsloan** [comment]
Will do. In the meantime, is there a known workaround for this?

**Comment by leastprivilege** [comment]
It's the first time I see this error. sorry.

Closing - please let us know the outcome of the issue at Microsoft.
