### ISSUE TITLE
Intermittent 'Invalid algorithm specified.' exception

### ISSUE THREAD

**Issue by andrewenable** [IdentityServer/IdentityServer3#3695]
We are currently experiencing an intermittent  'Invalid algorithm specified.' error in our production environment. 

Following a deployment, the sign-in process is successful and everything works as expected, however, several days later users are unable to login. If we redeploy the web application this seems to resolve the issue temporarily. We believe the certificates configured are correct as users are able to login successfully at times. 

The web application is hosted in a load balanced environment, these have the same machine key configured. Would anyone be able to advise what the cause of the issue might be? 

The exception we are getting is below:

```
[2017-05-12 11:16:03.0228]  -  ID :: 5000, NAME :: Unhandled exception, MESSAGE :: System.Security.Cryptography.CryptographicException: Invalid algorithm specified.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash, Int32 cbHash, ObjectHandleOnStack retSignature)
   at System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
   at System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] rgbHash, Int32 calgHash)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.CreateSignature(String inputString, SecurityKey key, String algorithm, SignatureProvider signatureProvider) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 854
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.WriteToken(SecurityToken token) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 815
   at IdentityServer3.Core.Services.Default.DefaultTokenSigningService.<SignAsync>d__11.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 129
```

[Log.txt](https://github.com/IdentityServer/IdentityServer3/files/1010197/Log.txt)

**Comment by Netsmurf** [comment]
HI andrewenable 
Did you identify what was causing this?

Thanks

**Comment by andrewenable** [comment]
The issue we had was caused by a separate part of the application making changes to the cryptoconfig:

`CryptoConfig.AddAlgorithm(typeof(RSAPKCS1SHA256SignatureDescription), "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256");`

This caused subsequent identity server requests to error. Updating to .NET framework 4.6.2 resolved the issue.

**Comment by thefringeninja** [comment]
@andrewenable did you just have to update the application server to 4.6.2 or did you compile against it as well?

**Comment by andrewenable** [comment]
Just the application server.

**Comment by thefringeninja** [comment]
thanks!
