### ISSUE TITLE
Problem to ConfigureUserServiceCache

### ISSUE THREAD

**Issue by sloukidis** [IdentityServer/IdentityServer3#3698]
- [✓] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
I am trying to register a custom UserService Cache but not working as expected. When Autofac tries to construct  UserService an error appears.

## IdentityServerServiceFactory
private IdentityServerServiceFactory ConfigureIdentityServiceFactory(string connString)
{

	// Database Connection
	var efConfig = new EntityFrameworkServiceOptions
	{
		ConnectionString = connString
	};
	// Create factory and register custom user service
	var factory = new IdentityServerServiceFactory
	{
		UserService = new Registration<IUserService, UserService>(),
		ViewService = new Registration<IViewService, IdentityViewService>()
	};
	// Register other services
	factory.RegisterConfigurationServices(efConfig);
	factory.RegisterOperationalServices(efConfig);
	// Configure cache
	factory.ConfigureClientStoreCache();
	factory.ConfigureScopeStoreCache();
	factory.ConfigureUserServiceCache(new Registration<ICache<IEnumerable<Claim>>, UserCacheService>());
	// Data Cleanup
	var cleanup = new TokenCleanup(efConfig, 300);
	cleanup.Start();
	// Return Factory
	return factory;

}
## UserService
 public class UserService : UserServiceBase
{

	private readonly IClientStore _clientStore;
	private readonly ICache<IEnumerable<Claim>> _claimCache;

	public UserService(IClientStore clientStore, ICache<IEnumerable<Claim>> claimCache)
	{
		_clientStore = clientStore;
		_claimCache = claimCache;
	}

	public override async Task GetProfileDataAsync(ProfileDataRequestContext context)
	{
		try
		{
			context.IssuedClaims = await GetClaimsAsync(context.Subject.GetSubjectId());
		}
		catch (Exception e)
		{
			Logging.LogFatal(e);
		}
	}

}
## UserCacheService

public class UserCacheService : ICache<IEnumerable<Claim>>

{

	public Task<IEnumerable<Claim>> GetAsync(string key)
	{
		
		throw new NotImplementedException();
	}

	public Task SetAsync(string key, IEnumerable<Claim> item)
	{
		throw new NotImplementedException();
	}

}

### Relevant parts of the log file
LibLog Error: 0 : [2017-05-19T07:48:29.9444345Z] Level=Error, Kind=End, Category='System.Web.Http.Controllers', Id=80000127-0006-fd00-b63f-84710c7967bb, Operation=DefaultHttpControllerActivator.Create, Exception=System.InvalidOperationException: An error occurred when trying to create a controller of type 'AuthenticationController'. Make sure that the controller has a parameterless public constructor. ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'IdentityServer.Services.UserService' can be invoked with the available services and parameters:
Cannot resolve parameter 'IdentityServer3.Core.Services.ICache`1[System.Collections.Generic.IEnumerable`1[System.Security.Claims.Claim]] claimCache' of constructor 'Void .ctor(IdentityServer3.Core.Services.IClientStore, IdentityServer3.Core.Services.ICache`1[System.Collections.Generic.IEnumerable`1[System.Security.Claims.Claim]])'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveNamed[TService](IComponentContext context, String serviceName, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveNamed[TService](IComponentContext context, String serviceName) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at IdentityServer3.Core.Services.Default.AutofacDependencyResolver.Resolve[T](String name) in c:\local\identity\server3\IdentityServer3\source\Core\Services\Default\AutofacDependencyResolver.cs:line 33
   at IdentityServer3.Core.Configuration.IdentityServerServiceFactoryExtensions.<ConfigureUserServiceCache>b__4(IDependencyResolver resolver) in c:\local\identity\server3\IdentityServer3\source\Core\Extensions\IdentityServerServiceFactoryExtensions.cs:line 166
   at IdentityServer3.Core.Configuration.Hosting.AutofacConfig.<>c__DisplayClass1a.<Register>b__17(IComponentContext ctx) in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\Hosting\AutoFacConfig.cs:line 317
   at Autofac.RegistrationExtensions.<>c__DisplayClass10`1.<Register>b__f(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.ResolvedParameter.<>c__DisplayClass6`1.<ForKeyed>b__5(ParameterInfo pi, IComponentContext c) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.ResolvedParameter.<>c__DisplayClass2.<CanSupplyValue>b__0() in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, Parameter[] parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at IdentityServer3.Core.Configuration.Hosting.AutofacConfig.<RegisterDecorator>b__15[T,TDecorator](IComponentContext ctx) in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\Hosting\AutoFacConfig.cs:line 264
   at Autofac.RegistrationExtensions.<>c__DisplayClass10`1.<Register>b__f(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Builder.RegistrationBuilder.<>c__DisplayClass1`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0() in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Registration.ExternalRegistrySource.<>c__DisplayClass8.<RegistrationsFor>b__3(IComponentContext c, IEnumerable`1 p) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Execute() in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.ResolutionExtensions.ResolveOptional(IComponentContext context, Type serviceType) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at Autofac.Integration.WebApi.AutofacWebApiDependencyScope.GetService(Type serviceType) in c:\local\identity\server3\IdentityServer3\source\Core\Internal\Autofac.Integration.Owin\AutofacAppBuilderExtensions.cs:line 0
   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   --- End of inner exception stack trace ---
   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at System.Web.Http.Tracing.Tracers.HttpControllerActivatorTracer.<>c__DisplayClass2.<System.Web.Http.Dispatcher.IHttpControllerActivator.Create>b__0() in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0
   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace) in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\DiscoveryEndpointController.cs:line 0

**Comment by lukos** [comment]
I think the problem is related to the use of generics in the cache class. Autofac has some special behaviour for generics: https://stackoverflow.com/questions/1189519/resolving-generic-interface-with-autofac, which I think means that although you have registered the user cache, you cannot inject it into the constructor of the UserService.

There might be other autofac methods available directly or with the extensions that idsrv provides that will do what you need.

Other options: 
# Resolve the cache directly from your userservice using the relevant autofac resolve overload.
# Simply build your user cache directly into the UserService and bypass autofac completely. Having injectable types is useful if you are providing one implementation and not the other but in this case, you are providing both, which can therefore be more tightly coupled.

**Comment by sloukidis** [comment]
Thanks @lukos for your answer.  I resolve the issue..
