### ISSUE TITLE
Windows Security Update KB4025344 conflicts with Identity Server 3 (System.Security.Cryptography.CryptographicException: Invalid algorithm specified)

### ISSUE THREAD

**Issue by AlinCiocan** [IdentityServer/IdentityServer3#3790]
### Identity Server 3 does not work on IIS with Windows Security update KB4025344

After receiving the Windows Security Update KB4025344 the Identity Server could not create tokens and throws "System.Security.Cryptography.CryptographicException: Invalid algorithm specified.".

One colleague of mine had the same issue and after uninstalling KB4025344 update, everything works fine. So it seems that this update conflicts with something from encryption algorithms that are used by Identity Server.

I have added the issue here in case someone has the same issue to know where is the problem.

### Relevant parts of the log file
```
[Error] Exception accessing: /IdentityServer/connect/authorize
System.Security.Cryptography.CryptographicException: Invalid algorithm specified.
```

### Log file
```
[Error] Exception accessing: /IdentityServer/connect/authorize
System.Security.Cryptography.CryptographicException: Invalid algorithm specified.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash, Int32 cbHash, ObjectHandleOnStack retSignature)
   at System.Security.Cryptography.Utils.SignValue(SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
   at System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] rgbHash, Int32 calgHash)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.CreateSignature(String inputString, SecurityKey key, String algorithm, SignatureProvider signatureProvider) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 854
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.WriteToken(SecurityToken token) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 815
   at IdentityServer3.Core.Services.Default.DefaultTokenSigningService.<SignAsync>d__11.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Services.Default.DefaultTokenSigningService.<CreateJsonWebToken>d__8.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Services.Default.DefaultTokenSigningService.<SignTokenAsync>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\Default\DefaultTokenSigningService.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Services.Default.DefaultTokenService.<CreateSecurityTokenAsync>d__c.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Services\Default\DefaultTokenService.cs:line 243
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.ResponseHandling.AuthorizeResponseGenerator.<CreateImplicitFlowResponseAsync>d__18.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.ResponseHandling.AuthorizeResponseGenerator.<CreateResponseAsync>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\ResponseHandling\AuthorizeResponseGenerator.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Endpoints.AuthorizeEndpointController.<CreateAuthorizeResponseAsync>d__12.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\AuthorizeEndpointController.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at IdentityServer3.Core.Endpoints.AuthorizeEndpointController.<ProcessRequestAsync>d__4.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\AuthorizeEndpointController.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityServer3.Core.Endpoints.AuthorizeEndpointController.<Get>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Endpoints\Connect\AuthorizeEndpointController.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.System.Web.Http910180.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext() in c:\local\identity\server3\IdentityServer3\source\Core\Configuration\DiscoveryOptions.cs:line 0
w3wp.exe Error: 0 : Unable to connect to any of the specified MySQL hosts.
```

**Comment by leastprivilege** [comment]
That seems to be a problem with the JWT handler from MS - @brentschmaltz

**Comment by prabhakarkk** [comment]
As the Windows update seems to Security Update, few of the Organization policies will not recommend to uninstalling these updates. Is there any plan to provide a fix in IdentityServer3 to support for this Windows Security Update

**Comment by leastprivilege** [comment]
As you can see in the stack trace, the error is coming from Microsoft's JWT lib. I will try to get the right MS people on this thread.

**Comment by brentschmaltz** [comment]
@leastprivilege @AlinCiocan do you know the algorithm being specified. The JWT header is all i need.

**Comment by AlinCiocan** [comment]
@brentschmaltz The JWT header is this:

```
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "a3rMUgMFv9tPclLa6yF3zAkfquE",
  "kid": "a3rMUgMFv9tPclLa6yF3zAkfquE"
}
```

**Comment by brentschmaltz** [comment]
@AlinCiocan Thanks, RS256 is what i expected to see. I should be able to figure this out now.

**Comment by etortec** [comment]
Has anyone encountered this bug on a system running a Windows version other than Windows 10 (e.g Windows Server)? 
If so I’d be very interested to see if we can track down the relevant KB updates to avoid.

**Comment by ahmetzeytindali** [comment]
Hi all, any workaround for this?

**Comment by VjParmar** [comment]
Try upgrading Microsoft.Owin.Security.OAuth and Microsoft.Owin.Security.Jwt to latest version and see if it works

**Comment by ahmetzeytindali** [comment]
Just installing The Microsoft .NET Framework 4.6.2 solved the problem. Thanks.

**Comment by AlinCiocan** [comment]
@ahmetzeytindali I have updated my .NET version from 4.6.1 to 4.6.2 and it worked for me also. Thanks.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by AlinCiocan** [comment]
@brockallen Yes, I think you can close the issue.

**Comment by oboforty** [comment]
Potential fix if your project's .net version can't be updated due to company policy or version conflicts:

Microsoft has a tool for disabling updates:
[](https://support.microsoft.com/en-us/help/3073930/how-to-temporarily-prevent-a-driver-update-from-reinstalling-in-window)

**Comment by MattMicro** [comment]
I'm updated my Identity Server project to use 4.6.2 but I am still having the same problem.

I updated all of my nuget packages to net462 by uninstalling them all and then installing them again against the new framework - went from 452 to 462:

<packages>
  <package id="IdentityServer3" version="2.6.1" targetFramework="net462" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.7" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Logging" version="1.1.4" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.1.4" targetFramework="net462" />
  <package id="Microsoft.Net.Compilers" version="2.3.1" targetFramework="net462" developmentDependency="true" />
  <package id="Microsoft.Owin" version="3.1.0" targetFramework="net462" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.1.0" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net462" />
  <package id="Owin" version="1.0" targetFramework="net462" />
  <package id="Serilog" version="2.5.0" targetFramework="net462" />
  <package id="Serilog.Sinks.Trace" version="2.1.0" targetFramework="net462" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.1.4" targetFramework="net462" />
</packages>

I've tried deleting all old packages, bin, obj folders, cleaning, rebuilding but still ending up with the same issue.

Am I missing something? Are you sure no other changes were done to get around the security update?

**Comment by MattMicro** [comment]
The issue might be related to a newer security update windows that got installed yesterday. After uninstalling it my identity server worked as expected again. So does the new security update stop identity server 3 working when on 4.6.2 framework? Does anyone have a solution for that? Unfortunately I deleted the update to see if it was causing the issue, but it was another KB40... I'll update when I find out what the full code was.

**Comment by AlinCiocan** [comment]
@MattMicro Could you post the new security KB number?

**Comment by MattMicro** [comment]
@AlinCiocan, the update causing the issue for me is: KB4034660

This updates gives the same error as the older update: KB4025344

I didn't get the chance to test the 4.6.2 upgrade against KB4025344 so I'm not sure if that would have fixed the issue for me or not anyway. But the newer update, KB4034660, is definitely causing the same issue again - even after the 4.6.2 update to my ID3 project. I'd guess KB4034660 is just a replace for KB4025344.

**Comment by chuleva** [comment]
Hello @MattMicro ,
Me and @AlinCiocan just installed the NET Framework 4.6.2.
The ID3 project is still compiled against net framework 4.5.2.

**Comment by MattMicro** [comment]
Hmmm, I assumed it was the projects that needed updating. I already have 4.6.2 installed... Maybe I should try re-installing it...

**Comment by MattMicro** [comment]
Just in case anybody else has the same issue as me. I had:

- Microsoft .NET Framework 4.6.2 SDK
- Microsoft .NET Framework 4.6.2 Targeting Pack

installed. After uninstalling and installing again, this time I have the above 2 programs installed but also:

- Microsoft .NET Framework 4.6.2 Targeting Pack (ENU)

It now all seems to work fine again. Thank you for your help.
