### ISSUE TITLE
Audience validation failed issue

### ISSUE THREAD

**Issue by chanpod** [IdentityServer/IdentityServer3#3806]
I have my issuer set in our 3rd party program that generates our tokens and the IssuerName set in IdenetityServer3 

```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://ialsecureauth.com/SecureAuth2",
                RequiredScopes = new[] { "openid", "email", "profile" },
                ClientId = REDACTED, //Do I even need this for this scenario?
                IssuerName = "MyAudience",
                
            });
```

```
System.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'MyAudience'. Did not match:  validationParameters.ValidAudience: 'MyAudience/resources' or validationParameters.ValidAudiences: 'null'
   at System.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\Validators.cs:line 92
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 1179
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 702
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
    ProcessId=14848
    DateTime=2017-08-07T14:43:22.7980713Z

```

I'm still learning so if anything is wrong, just let me know. But the issue I'm noticing is it's adding /resource to the audience. How am I supposed to get around that? I tried setting my Issuer (in the 3rd party app) to include /resource, but then I got the same error but instead of MyAudience/resources I got MyAudience/resources/resources 😕

**Comment by brockallen** [comment]
Issuer and Audience are two different things.

**Comment by chanpod** [comment]
Fair enough (I knew that, just derped). This doesn't fix the issue though. I only added that in hopes that it needed b/c this issue persisted. I don't see any fields in the options for specify an audience though. It seems to be pulling audience from the access token, slapping /resources on to it, and then getting mad b/c it doesn't match. 

https://github.com/identityserver/IdentityServer3.AccessTokenValidation

Shows a pretty simple setup, and I did that originally. All the extra stuff has just been to try and get around this. 

This doesn't have anything to do with the issuing server not being an identityserver does it? I would guess not. It's all oauth/openid connect. So it should work together?

I will note that this is a .net web api server running 4.5.

**Comment by chanpod** [comment]
I was looking at the nuget packages, and noticed that the IdentityServer3.AccessTokenValidation package description says "Access token validation middleware for JWT and reference tokens _issued by IdentityServer3_"

Does this mean that it can't validate tokens issued from other sources? 

That asked, I also found IdentityServer3.AccessTokenValidation.Integration.AspNet

I installed it but it didn't seem to change anything. And the links to the repo return a 404 sadly. I'm beginning to think I can't use this. Which is super disappointing as it's exactly what I need.

**Comment by brockallen** [comment]
I still don't understand why you've set the IssuerName to be your API's audience value. Or is that a typo?

**Comment by chanpod** [comment]
That was just a place holder. This issue persist even when my config looks like this

```
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://ialsecureauth.com/SecureAuth2"
            });)
```

**Comment by chanpod** [comment]
I think maybe this is part of the issue now that I think about it. 
We're using SecureAuth to generate our JWT token. Which is using OIDC. My issuer is actually set to IAL. The error then says.

```
Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Error: 0 : Authentication failed
System.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'IAL'. Did not match:  validationParameters.ValidAudience: 'IAL/resources' or validationParameters.ValidAudiences: 'null'
   at System.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\Validators.cs:line 92
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 1179
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 702
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
    ProcessId=17880
    DateTime=2017-08-07T18:49:01.3098163Z
```

 I have done nothing to set my audience value. I would love to do that though. But I don't see any place to do it in IdentityServer3 when you're just configuring bearer token authentication. It's assuming my audience. But it's doing something weird and getting mad about it.

**Comment by chanpod** [comment]
Hey guys, I know your busy, but I feel this is probably a simple solution or answer. If this doesn't work I'll have to manually do this which isn't great but you do what you gotta do :)

I think I've narrowed down my question to this. 

Can I modify the expected audience when just using the IdentityServerBearerTokenAuthenticationOptions portion of identity server 3?

**Comment by brockallen** [comment]
Don't set issuer -- that's automatically set from the STS' metadata. You want to either set audience or the allowed scopes to ensure the access token is allowed to be used in your API.

**Comment by chanpod** [comment]
It seems the 3rd party token generation we're using doesn't seem compatible with this library. I've set the allowed scopes, I've used bare bones settings, and I've tried setting all relevant fields and nothing will get past the audience issue. Thanks for your help. If I discover something new or figure out how to get past this I'll update this issue. But I'll close for now.
