### ISSUE TITLE
The requested resource does not support http method 'OPTIONS' (405 Error)

### ISSUE THREAD

**Issue by kansberry** [IdentityServer/IdentityServer3#3845]
We have created an MVC web application using IdentityServer3 and OpenIdConnect. The configuration of this is shown below and works without issue until the authenication cookie expires (i.e. basically copied it from a IdentityServer sample). When cookie expires based on expiration of "AuthenticationTicket" matching the expiration of the Identity Token, the next call to the "connect/authorize" endpoint, presumably in the OpenId Connect middleware, appears to reject the OPTIONS pre-flight call stating the method is not supported. Unsure why it works on the first iteration and not on the second. Is is possible the the OPTIONS request is not being sent during the first iteration? I am assuming a pre-flight is needed and sent for both calls, but you can correct me if I am wrong. I have posted the log file from IdentityServer below as well to hopefully give someone the information they need to help me solve this problem.

I guess I should also mention that IdentityServer is configured to use ASP Identity like this:

            factory.RegisterConfigurationServices(entityFrameworkConfigOptions);
            factory.RegisterOperationalServices(entityFrameworkConfigOptions);
            factory.Register(new Registration<IdentityDbContext>());
            factory.Register(new Registration<UserStore<IdentityUser>>());
            factory.Register(new Registration<UserManager<IdentityUser, string>>(x=> new UserManager<IdentityUser>(x.Resolve<UserStore<IdentityUser>>())));

And the "Cors" tab of the client application (i.e. ClientCorsOrigins table) has the following entries:

http://10.1.5.106/
http://10.1.5.106/MyApp/Render
http://10.1.5.106
http://10.1.5.106/MyApp/Render/

Finally, the configuration of OWIN authentication looks like this:

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                CookieName = "MyApp"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = authorizationUrl,
                ClientId = authorizationClientId,
                ClientSecret = authorizationClientSecret,
                RedirectUri = authorizationRedirectUri,
                ResponseType = "code id_token",
                Scope = "openid profile offline_access MyScope",
                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role"
                },
                SignInAsAuthenticationType = "Cookies",
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    AuthorizationCodeReceived = async context =>
                    {
                        // use the code to get the access and refresh token
                        var tokenClient = new TokenClient(new Uri(new Uri(authorizationUrl), "connect/token").ToString(), authorizationClientId, authorizationClientSecret);
                        var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(context.Code, context.RedirectUri);
                        if (tokenResponse.IsError) throw new Exception(tokenResponse.Error);
                        // use the access token to retrieve claims from userinfo
                        var userInfoClient = new UserInfoClient(new Uri(new Uri(authorizationUrl), "connect/userinfo").ToString());
                        var userInfoResponse = await userInfoClient.GetAsync(tokenResponse.AccessToken);
                        // create new identity
                        var claimsIdentity = new ClaimsIdentity(context.AuthenticationTicket.Identity.AuthenticationType);
                        claimsIdentity.AddClaims(userInfoResponse.Claims);
                        claimsIdentity.AddClaim(new System.Security.Claims.Claim("access_token", tokenResponse.AccessToken));
                        claimsIdentity.AddClaim(new System.Security.Claims.Claim("expires_at", DateTime.Now.AddSeconds(tokenResponse.ExpiresIn).ToLocalTime().ToString()));
                        claimsIdentity.AddClaim(new System.Security.Claims.Claim("refresh_token", tokenResponse.RefreshToken));
                        claimsIdentity.AddClaim(new System.Security.Claims.Claim("id_token", context.ProtocolMessage.IdToken));
                        claimsIdentity.AddClaim(new System.Security.Claims.Claim("sid", context.AuthenticationTicket.Identity.FindFirst("sid").Value));
                        // create authentication ticket
                        context.AuthenticationTicket = new AuthenticationTicket(new ClaimsIdentity(claimsIdentity.Claims, context.AuthenticationTicket.Identity.AuthenticationType, "name", "role"), context.AuthenticationTicket.Properties);
                    },
                    RedirectToIdentityProvider = context =>
                    {
                        // if signing out, add the id_token_hint
                        if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = context.OwinContext.Authentication.User.FindFirst("id_token");
                            if (idTokenHint != null)
                            {
                                context.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }
                        }
                        return Task.FromResult(0);
                    }
                }
            });

### Relevant parts of the log file

```
2017-08-31 15:38:28,425 [17] [] INFO  618398  IdentityServer3.Core.Configuration.Hosting.CorsPolicyProvider+<GetCorsPolicyAsync>d__0.MoveNext  - CORS request made for path: /connect/authorize from origin: http://10.1.5.106 but rejected because invalid CORS path
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - HTTP Request
{
  "Method": "OPTIONS",
  "Url": "https://csp60pq.gisv.local/connect/authorize?client_id=Cincom.CPQ.ISS&redirect_uri=http%3a%2f%2f10.1.5.106%2fRenderPrototype%2fRender&response_mode=form_post&response_type=code+id_token&scope=openid+profile+offline_access+Cincom.CPQ&state=OpenIdConnect.AuthenticationProperties%3dw2_feLYBRd6c9a6p0C7EV_qrEPw9n4WMviiaZnD78I9oCnvsKh4gpW_vXDkccYkW_K5qSaIK49lxnqFyABu9g57CfgNbh-yvvpMBDD7-CeVjjJvuqm7GleCmu0WuQsurwufFw4s0Zv-UDlJUNcJMP6usQXCCDP5tB2hPXgeXiYv_u0KE2Flo2gMxDKQYhDH5s1SJk8BZeJlQbqgeg0r14NM282SK8yGyIqdxt3dVOxYPqJ2yABvcqSYXnhxO7lNgIEPVaCWhplUq3duFEZlgkCQwYxom_q1xzQRKSwYWpVU&nonce=636398051083158107.MmQ5MTRmYTgtMjA5MS00NGUwLTg2MzEtZjc4MDVkYjMyNDM0NGUyN2QyNjktMDUzNS00YTk3LWJlMWYtZWFlZjhiYTA3ODE2",
  "Headers": {
    "Connection": [
      "keep-alive"
    ],
    "Accept": [
      "*/*"
    ],
    "Accept-Encoding": [
      "gzip, deflate, br"
    ],
    "Accept-Language": [
      "en-US,en;q=0.8"
    ],
    "Host": [
      "csp60pq.gisv.local"
    ],
    "Referer": [
      "http://10.1.5.106/RenderPrototype/Render?SiteName=CincomCPQ&ApplicationName=SalesPortal&PageName=SalesPortal&Route=Opportunities&SessionId=2bdd78bb-eb84-4e93-9100-fa427c96c663"
    ],
    "User-Agent": [
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
    ],
    "Access-Control-Request-Method": [
      "GET"
    ],
    "Origin": [
      "http://10.1.5.106"
    ],
    "Access-Control-Request-Headers": [
      "content-type,x-requested-with"
    ]
  },
  "Body": ""
}
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4256634Z] Request received, Method=OPTIONS, Url=https://csp60pq.gisv.local/connect/authorize?client_id=Cincom.CPQ.ISS&redirect_uri=http:%2f%2f10.1.5.106%2fRenderPrototype%2fRender&response_mode=form_post&response_type=code+id_token&scope=openid+profile+offline_access+Cincom.CPQ&state=OpenIdConnect.AuthenticationProperties%3dw2_feLYBRd6c9a6p0C7EV_qrEPw9n4WMviiaZnD78I9oCnvsKh4gpW_vXDkccYkW_K5qSaIK49lxnqFyABu9g57CfgNbh-yvvpMBDD7-CeVjjJvuqm7GleCmu0WuQsurwufFw4s0Zv-UDlJUNcJMP6usQXCCDP5tB2hPXgeXiYv_u0KE2Flo2gMxDKQYhDH5s1SJk8BZeJlQbqgeg0r14NM282SK8yGyIqdxt3dVOxYPqJ2yABvcqSYXnhxO7lNgIEPVaCWhplUq3duFEZlgkCQwYxom_q1xzQRKSwYWpVU&nonce=636398051083158107.MmQ5MTRmYTgtMjA5MS00NGUwLTg2MzEtZjc4MDVkYjMyNDM0NGUyN2QyNjktMDUzNS00YTk3LWJlMWYtZWFlZjhiYTA3ODE2, Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='https://csp60pq.gisv.local/connect/authorize?client_id=Cincom.CPQ.ISS&redirect_uri=http:%2f%2f10.1.5.106%2fRenderPrototype%2fRender&response_mode=form_post&response_type=code+id_token&scope=openid+profile+offline_access+Cincom.CPQ&state=OpenIdConnect.AuthenticationProperties%3dw2_feLYBRd6c9a6p0C7EV_qrEPw9n4WMviiaZnD78I9oCnvsKh4gpW_vXDkccYkW_K5qSaIK49lxnqFyABu9g57CfgNbh-yvvpMBDD7-CeVjjJvuqm7GleCmu0WuQsurwufFw4s0Zv-UDlJUNcJMP6usQXCCDP5tB2hPXgeXiYv_u0KE2Flo2gMxDKQYhDH5s1SJk8BZeJlQbqgeg0r14NM282SK8yGyIqdxt3dVOxYPqJ2yABvcqSYXnhxO7lNgIEPVaCWhplUq3duFEZlgkCQwYxom_q1xzQRKSwYWpVU&nonce=636398051083158107.MmQ5MTRmYTgtMjA5MS00NGUwLTg2MzEtZjc4MDVkYjMyNDM0NGUyN2QyNjktMDUzNS00YTk3LWJlMWYtZWFlZjhiYTA3ODE2'
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4256634Z] Level=Info, Kind=Begin, Category='System.Web.Http.MessageHandlers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=DependencyScopeHandler.SendAsync
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4256634Z] Level=Info, Kind=Begin, Category='System.Web.Http.MessageHandlers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=PassiveAuthenticationMessageHandler.SendAsync
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4256634Z] Level=Info, Kind=Begin, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='Route='controller:AuthorizeEndpoint,action:Get'', Operation=DefaultHttpControllerSelector.SelectController
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4256634Z] Level=Info, Kind=End, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='AuthorizeEndpoint', Operation=DefaultHttpControllerSelector.SelectController
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4256634Z] Level=Info, Kind=Begin, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=HttpControllerDescriptor.CreateController
2017-08-31 15:38:28,425 [17] [] DEBUG 618398  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4256634Z] Level=Info, Kind=Begin, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=DefaultHttpControllerActivator.Create
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=End, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='IdentityServer3.Core.Endpoints.AuthorizeEndpointController', Operation=DefaultHttpControllerActivator.Create
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=End, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='IdentityServer3.Core.Endpoints.AuthorizeEndpointController', Operation=HttpControllerDescriptor.CreateController
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=Begin, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=AuthorizeEndpointController.ExecuteAsync
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=Begin, Category='System.Web.Http.Action', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=ApiControllerActionSelector.SelectAction
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=Begin, Category='System.Net.Http.Formatting', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='Type='HttpError', formatters=[JsonMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer, FormUrlEncodedMediaTypeFormatterTracer]', Operation=DefaultContentNegotiator.Negotiate
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=Begin, Category='System.Net.Http.Formatting', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='Obtaining formatter of type 'JsonMediaTypeFormatter' for type='HttpError', mediaType='application/json; charset=utf-8'', Operation=JsonMediaTypeFormatter.GetPerRequestFormatterInstance
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=End, Category='System.Net.Http.Formatting', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='Will use same 'JsonMediaTypeFormatter' formatter', Operation=JsonMediaTypeFormatter.GetPerRequestFormatterInstance
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Info, Kind=End, Category='System.Net.Http.Formatting', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='Selected formatter='JsonMediaTypeFormatter', content-type='application/json; charset=utf-8'', Operation=DefaultContentNegotiator.Negotiate
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Warn, Kind=End, Category='System.Web.Http.Action', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='UserMessage='The requested resource does not support http method 'OPTIONS'.'', Operation=ApiControllerActionSelector.SelectAction, Status=405 (MethodNotAllowed), Exception=System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.Tracing.Tracers.HttpActionSelectorTracer.<>c__DisplayClass2.<System.Web.Http.Controllers.IHttpActionSelector.SelectAction>b__0()
   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace)
2017-08-31 15:38:28,441 [17] [] DEBUG 618414  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4412734Z] Level=Warn, Kind=End, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='UserMessage='The requested resource does not support http method 'OPTIONS'.'', Operation=AuthorizeEndpointController.ExecuteAsync, Status=405 (MethodNotAllowed), Exception=System.Web.Http.HttpResponseException: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
   at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.Tracing.Tracers.HttpActionSelectorTracer.<>c__DisplayClass2.<System.Web.Http.Controllers.IHttpActionSelector.SelectAction>b__0()
   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace)
   at System.Web.Http.Tracing.Tracers.HttpActionSelectorTracer.System.Web.Http.Controllers.IHttpActionSelector.SelectAction(HttpControllerContext controllerContext)
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4569009Z] Level=Info, Kind=End, Category='System.Web.Http.MessageHandlers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=PassiveAuthenticationMessageHandler.SendAsync, Status=405 (MethodNotAllowed)
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4569009Z] Level=Info, Kind=End, Category='System.Web.Http.MessageHandlers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=DependencyScopeHandler.SendAsync, Status=405 (MethodNotAllowed)
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4569009Z] Sending response, Status=405 (MethodNotAllowed), Method=OPTIONS, Url=https://csp60pq.gisv.local/connect/authorize?client_id=Cincom.CPQ.ISS&redirect_uri=http:%2f%2f10.1.5.106%2fRenderPrototype%2fRender&response_mode=form_post&response_type=code+id_token&scope=openid+profile+offline_access+Cincom.CPQ&state=OpenIdConnect.AuthenticationProperties%3dw2_feLYBRd6c9a6p0C7EV_qrEPw9n4WMviiaZnD78I9oCnvsKh4gpW_vXDkccYkW_K5qSaIK49lxnqFyABu9g57CfgNbh-yvvpMBDD7-CeVjjJvuqm7GleCmu0WuQsurwufFw4s0Zv-UDlJUNcJMP6usQXCCDP5tB2hPXgeXiYv_u0KE2Flo2gMxDKQYhDH5s1SJk8BZeJlQbqgeg0r14NM282SK8yGyIqdxt3dVOxYPqJ2yABvcqSYXnhxO7lNgIEPVaCWhplUq3duFEZlgkCQwYxom_q1xzQRKSwYWpVU&nonce=636398051083158107.MmQ5MTRmYTgtMjA5MS00NGUwLTg2MzEtZjc4MDVkYjMyNDM0NGUyN2QyNjktMDUzNS00YTk3LWJlMWYtZWFlZjhiYTA3ODE2, Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='Content-type='application/json; charset=utf-8', content-length=unknown'
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4569009Z] Level=Info, Kind=Begin, Category='System.Net.Http.Formatting', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Message='Value='System.Web.Http.HttpError', type='HttpError', content-type='application/json; charset=utf-8'', Operation=JsonMediaTypeFormatter.WriteToStreamAsync
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4569009Z] Level=Info, Kind=End, Category='System.Net.Http.Formatting', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=JsonMediaTypeFormatter.WriteToStreamAsync
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4569009Z] Level=Info, Kind=Begin, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=AuthorizeEndpointController.Dispose
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - [2017-08-31T19:38:28.4569009Z] Level=Info, Kind=End, Category='System.Web.Http.Controllers', Id=c78ef9cd-85bc-4a3a-8c63-ff269aada217, Operation=AuthorizeEndpointController.Dispose
2017-08-31 15:38:28,456 [17] [] DEBUG 618429  IdentityServer3.Core.Logging.LogExtensions.Debug  - HTTP Response
{
  "StatusCode": 405,
  "Headers": {
    "Content-Type": [
      "application/json; charset=utf-8"
    ],
    "Server": [
      "Microsoft-IIS/8.5"
    ],
    "Allow": [
      "GET"
    ],
    "Content-Length": [
      "76"
    ]
  },
  "Body": "{\"Message\":\"The requested resource does not support http method 'OPTIONS'.\"}"
}
```

**Comment by laksh-parab** [comment]
I am having the same issue. Have you able to find the solution?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
